### ISSUE TITLE
[gatsby-transformer-sharp] `cropFocus: attention` seems broken in example site

### ISSUE THREAD

**Issue by dustinhorton** [gatsbyjs/gatsby#10178]
Screenshot below is from [https://image-processing.gatsbyjs.org](https://image-processing.gatsbyjs.org):

<img width="661" alt="screen shot 2018-11-28 at 2 56 25 am" src="https://user-images.githubusercontent.com/378165/49140220-57295c00-f2b9-11e8-9131-028dacf3477e.png">

It states:

> The default is `ATTENTION`, which the Sharp documentation describes as "focus on the region with the highest luminance frequency, colour saturation and presence of skin tones" – which is why we actually see Mr. Gatsby toasting to us in the first thumbnail

But you'll notice in my screenshot that we don't see him toasting.

### Expected result

We should see him

### Actual result

We see the same as the `cropFocus: ENTROPY` example

**Comment by dustinhorton** [comment]
Replying to keep it open. Still busted.

**Comment by LekoArts** [comment]
Normally this should be fixed: https://github.com/gatsbyjs/gatsby/pull/4253
Weird. @pieh any idea?

**Comment by denzo** [comment]
@AishaBlake I'm still seeing the issue

https://image-processing.gatsbyjs.org/

![image](https://user-images.githubusercontent.com/1874772/85177130-cc56ea80-b2be-11ea-9f35-18751a187464.png)

**Comment by robations** [comment]
We could do with face detection as an option. I keep getting people's heads being chopped off as the algorithm gravitates to an area that happens to be high contrast/entropy, whether using ENTROPY or ATTENTION.

I tracked the crop feature back and it is the `smartcrop` feature in libvips that seems to be used. So any improvements would either have to come from libvips through sharp, or be implemented directly in gatsby-image.

See https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html for behaviour with various face detection algorithms.

**Comment by polarathene** [comment]
@robations such a feature [isn't available with `sharp`](https://sharp.pixelplumbing.com/api-resize), you'd need to request it to be added on the `sharp` project instead. `sharp` does provide `entropy` and `attention` [which seem to be the same thing roughly](https://github.com/libvips/libvips/issues/317#issuecomment-250688374), see that link for more information about the support being added to `libvips` (prior to `smartcrop.js` using it, which had inspired the issue/request). Originally libvips had similar issue as `sharp` produces with `attention`, but they [revisited that](https://github.com/libvips/libvips/issues/619) to mirror `smartcrop.js` results.

I haven't checked, but that would suggest that `sharp`'s `attention` crop mode might be using it's own implementation instead of deferring to `libvips` version of it.

In all cases though, including with `smartcrop.js`, I don't think `attention` is meant to be optimized for faces, so if it's not working well, it may [still be doing as expected](https://sharp.pixelplumbing.com/api-resize)(more detailed explanation of [the feature as implemented in `sharp` here](https://github.com/lovell/sharp/issues/295#issuecomment-253203168)):

> `attention`: focus on the region with the highest luminance frequency, colour saturation and presence of skin tones.

Which'd explain your example of `smartcrop.js` deferring face detection to third-party libs. You could request face detection support perhaps as a strategy for `sharp`? Or if you can pre-process the images you could get the crop dimensions yourself? 

In one of my projects, I cannot easily process the original images in one pass at build, but need to pre-process them(I have a small JS script that uses `sharp` directly, unrelated to Gatsby), then I leave Gatsby to handle making different sizes and image formats. Maybe that'd work for you too?

---

**EDIT:** `sharp` has been using `libvips` 8.5 `attention` crop strategy [since `sharp` 0.18](https://github.com/lovell/sharp/issues/727) (May 2017).
