### ISSUE TITLE
Webpack error when running `gatsby develop`

### ISSUE THREAD

**Issue by dvonlehman** [gatsbyjs/gatsby#11599]
When running `gatsby develop` it fails with the following error:

```
info bootstrap finished - 11.89 s

here ./.cache/develop-static-entry.js
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
TypeError: Cannot read property 'options' of undefined
    at getCustomOptions (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/gatsby/dist/utils/babel-loader-helpers.js:27:42)
    at Object.customOptions (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/gatsby/dist/utils/babel-loader.js:34:12)
    at Object.<anonymous> (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:91:52)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:5:364
    at Promise._execute (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.<anonymous> (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:220:18)
    at Object.loader (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:56:18)
    at Object.<anonymous> (/Users/davidvonlehman/src/aerobatic/marketing/website-gatsby/node_modules/babel-loader/lib/index.js:51:12)
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.app/debug-html

  14 |                          l: false,
  15 |                          exports: {}
> 16 |                  };
     | ^
  17 |
  18 |                  // Execute the module function
  19 |                  modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);


  WebpackError: ./.cache/develop-static-entry.js

  - bootstrap:16 getCustomOptions
    lib/webpack/bootstrap:16:1




  - universalModuleDefinition:3 asyncGeneratorStep
    lib/webpack/universalModuleDefinition:3:1

  - universalModuleDefinition:5 _next
    lib/webpack/universalModuleDefinition:5:1

  - universalModuleDefinition:5
    lib/webpack/universalModuleDefinition:5:1



  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - universalModuleDefinition:5 Object.<anonymous>
    lib/webpack/universalModuleDefinition:5:1


  - bootstrap:45 Object.loader
    lib/webpack/bootstrap:45:1

  - bootstrap:40 Object.<anonymous>
    lib/webpack/bootstrap:40:1
```

I've deleted the `.cache` and the `node_modules` directories and re-run `yarn` multiple times, but keep getting the same error.

**Comment by sidharthachatterjee** [comment]
Sorry you're seeing this @dvonlehman 

Can you please link to a minimal reproduction if possible?

**Comment by dvonlehman** [comment]
This was resolved by #11637

**Comment by prokopious** [comment]
Gatsby sites break way too easily.

**Comment by Aryaman73** [comment]
I'm still encountering this issue on Gatsby v 4.0.2. I've tried the NODE_ENV techniques as well.
