### ISSUE TITLE
Installation instructions wrong in Gatsby Themes Getting Started - Repo not found

### ISSUE THREAD

**Issue by deadcoder0904** [gatsbyjs/gatsby#13481]
Goto https://www.gatsbyjs.org/docs/themes/getting-started & try

```
gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme
```

Error is

```
Cloning into 'my-blog'...
remote: Repository not found.
```

**Comment by KartSriv** [comment]
Thank you @deadcoder0904 for pointing out this issue! You are right, the link has been changed to https://github.com/gatsbyjs/gatsby-starter-blog/. I'll fix it ASAP.

**Comment by KartSriv** [comment]
Fixed! Please wait for the reviewers to accept the changes. Thanks!

**Comment by LekoArts** [comment]
@KartSriv For future PRs: I wouldn't close the issue myself but let it be closed by the PR. Because this really isn't really fixed/solved until the PR is merged. Just wanted to let you know :)

**Comment by LekoArts** [comment]
However, looking at this issue in more detail I think we should close this without further action. The theme docs are currently WIP and not "public" (hence not in the sidebar) so this repository will eventually exist. Replacing the link with another repository doesn't really make sense as the instructions below would need to be adjusted, too, and the repository actually needs to contain a theme.

@gatsbyjs/themes-core will surely add the repository soon. Thank you for opening the issue!

**Comment by KartSriv** [comment]
@LekoArts Got it, Thanks!
