### ISSUE TITLE
Blog starter fails to start

### ISSUE THREAD

**Issue by bep** [gatsbyjs/gatsby#1390]
Continuing #1385

```bash
▶ gatsby develop
A local install of Gatsby exists but failed to load.
[SyntaxError: Unexpected token ...]
```

This is with:

```
npm install -g gatsby@latest
gatsby new gatsby-site
cd gatsby-site
gatsby develop
```

I assume this may be that I have some "old" stuff hanging around, which I may or may not get to clean up in the future, but I thought I should give you a heads up.

**Comment by whmountains** [comment]
Works for me, so I agree that you must have some old stuff hanging around.

What do you get when you run `gatsby --version`?  I helped someone update gatsby and we had very similar symptoms.  NPM kept saying that it had installed the latest version but gatsby wasn't getting upgraded.

**Comment by KyleAMathews** [comment]
Ugh, I hadn't actually updated the starters' package.jsons. Thanks for keeping on my case @bep :-D

**Comment by KyleAMathews** [comment]
This seems fixed now so closing. Lemme know if not @bep!

**Comment by bep** [comment]
It still fails for me (not sure what I need to remove/reinstall to get it up and running). I understand that the npm world adds loads of flexibility, but adds some pain, i.e. there is no such thing as a single binary. 

This looks like a very interesting project, but I will wait closer to 1.0 until I take it for another spin.

**Comment by streger** [comment]
I'm on linux mint and I'm getting this with with gatsby and gatsby-latest.
The only thing that is in the log as a warning is:
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by Stefanos-Stefanidis** [comment]
remove gatsby` npm -g uninstall gatsby --save `.Update your npm and node to latest version! After that follow [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions )  and re install gatsby! That did the trick for me

**Comment by streger** [comment]
Thanks, that did it.
ran those:
```
sudo npm -g uninstall gatsby
sudo npm cache clean -f
sudo npm install npm@latest -g
sudo npm install -g n
sudo n latest
sudo chown -R $(whoami) /usr/local/bin
sudo chown -R $(whoami) /usr/local/share
sudo chown -R $(whoami) /usr/local/node_modules
npm install -g gatsby@latest
gatsby new gatsby-site
cd gatsby-site
gatsby develop
```
