### ISSUE TITLE
[gatsby-source-wordpress] - GraphQL Error - Unknown Field on ACF

### ISSUE THREAD

**Issue by yaroslav-perec** [gatsbyjs/gatsby#13931]
Hi!

I have WP posts that have some optional fields, for example (`image1`, `image2`) and one file (for example `article.js`) in which I render these posts (they are grouped by category) when I leave some fields empty in one of the posts, I get the error message `Unknown field 'image' for type 'wordpress__POSTAcf`

I added this code to the end of my theme's functions.php file to fix my problem.

```
if (!function_exists('acf_nullify_empty')) {
  function acf_nullify_empty($value, $post_id, $field) {
    if (empty($value)) {
      return null;
    }
    return $value;
  }
}

add_filter('acf/format_value', 'acf_nullify_empty', 100, 3);
```
The problem is fixed when at least in one post all fields are filled. If all posts don't contain some field (for example, `image2`), I still have this error.

How do you think this behavior is ok?

**Comment by tombunnvivid** [comment]
From what I can tell you have to have one instance of a field populated for non-required ACF fields on the site on any page it will work.

This is more evident if you use flexible content fields. The query will fail on build unless all content module are used across the site. I believe it is a limitation of GraphQl and there isn't a way around it (at least for fragments). However, i'm having difficulty finding more information on this.

For now I'd advise trying to make a demo page where the field is populated and then exclude it from being published in your gatsby-node.js

**Comment by yaroslav-perec** [comment]
@tombunnvivid Thanks!!

**Comment by amcc** [comment]
I've the same issue, and it is fixed by having a single post filled as suggested, _however_, the README for gatsby-source-wordpress has a guide for setting fields to null if they're empty. I thought this might fix this error, though it doesn't. The following code is in a custom plugin:

````
if (!function_exists('acf_nullify_empty')) {
	/**
	 * Return `null` if an empty value is returned from ACF.
	 *
	 * @param mixed $value
	 * @param mixed $post_id
	 * @param array $field
	 *
	 * @return mixed
	 */
	function acf_nullify_empty($value, $post_id, $field) {
			if (empty($value)) {
					return null;
			}
			return $value;
	}
}
add_filter('acf/format_value', 'acf_nullify_empty', 100, 3);
````

**Comment by amcc** [comment]
After a bit more testing - it seems to be the case that if you dont have the code above then any empty ACF fields in a post can cause the 'Unknown field...' error even if there are some posts with that same ACF field filled. This is certainly the case with the site i'm testing. 

Having the above code in a simple plugin will fix this error, but it does require having at least one post with those fields present.

Without the above code (as well as the develop error) I was not seeing the ACF field that was sometimes emtpy in posts within GraphiQL, but with the above code in a plugin the field showed up.

I would still say this is a fairly critical error that might want to be addressed - i'm completely new to submitting contributing to Gatsby, but would like to see an update to the docs for gatsby-source-wordpress to reflect this and would be keen to submit something myself. Before I get to that stage, perhaps other people can chip in with their experience here to see if I have the complete story.

**Comment by iamkratos** [comment]
I've experiencing the same issue. The Gatsby docs function snippet isn't working for me, as my repeaters are still not showing up in the GraphQL explorer tab. I've tried gatsby clean, and restarting a few times, but it hasn't worked. Was anyone able to move past this one?
