### ISSUE TITLE
Routing working on local machine, but not on Netlify...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14758]
## Description

My repo:

https://github.com/arrowgtp/alma

...works fine on my local machine using `gatsby develop`.

But when I upload to Netlify, the router seems to break or can't find the routes properly at this url:

www.alma.vacations

Not sure what to do, except revert to an earlier build that works properly.

### Steps to reproduce

Clone the repo, run locally to check if it works, then upload it to Netlify to see if the routing is broken.

### Expected result

The routing on the served site should work properly.

### Actual result

The routing is broken and every route gives me a 404.

### Environment

```bash
System:
    OS: macOS 10.14.5
    CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.8.2 => 2.8.2 
    gatsby-cli: ^2.6.5 => 2.6.5 
    gatsby-image: ^2.1.2 => 2.1.2 
    gatsby-mdx: ^0.6.3 => 0.6.3 
    gatsby-plugin-intl: ^0.1.7 => 0.1.7 
    gatsby-plugin-layout: ^1.0.15 => 1.0.15 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-netlify: ^2.0.17 => 2.0.17 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.1.3 => 2.1.3 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-plugin-transition-link: ^1.12.4 => 1.12.4 
    gatsby-plugin-transitions: ^1.8.12 => 1.8.12 
    gatsby-plugin-twitter: ^2.0.13 => 2.0.13 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.0.38 => 2.0.38 
    gatsby-source-instagram: ^0.5.0 => 0.5.0 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.21 => 2.1.21 
    gatsby-transformer-yaml: ^2.1.12 => 2.1.12 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
```

**Comment by rchrdnsh** [comment]
hmmmm, now the routes are not working on either my local machine or netlify, so they are just broke, but no errors anywhere that I can find...

**Comment by valse** [comment]
The routing is working properly on Netlify :-\

**Comment by rchrdnsh** [comment]
whoops, forgot I switched to an earlier deploy. Should be broke again.

**Comment by rchrdnsh** [comment]
on the advice of one of the plugins I'm using, I reverted the gatsby version to 2.8.6 and the issue went away, so it is probably an issue between gatsby 2.9.x and this other plugin in some way.

**Comment by rchrdnsh** [comment]
argh, back to the same problem again...even with reverting...works on my local machine, but is broken on the netlify cdn...

**Comment by valse** [comment]
If you build and serve locally (usually port 9000) do you have the same problem?

**Comment by rchrdnsh** [comment]
port 8000 for me, and it works on localhost:8000, but not on the deployed site.

**Comment by valse** [comment]
You can check the production version locally too with `gatsby build` and `gatsby serve` commands...

**Comment by GuillaumeAmat** [comment]
I can confirm the issue. It seems that I was looking for the same thing:

- I've got a local Gatsby with pages and dynamic routes handled by `@reach/router`
- With the Gatsby dev server, all is working fine
- With `gatsby serve` Netlify, the dynamic routes break

Eg: `/my-page/my-dynamic-route` becomes `/my-page/` when I visit the complete (first) URL.

It seems that the bug has been created in the 2.9.0 version. Downgrading to 2.8.8 fix it for me.

**Comment by valse** [comment]
This is the same issue #14742

**Comment by GuillaumeAmat** [comment]
Oh, thanks for the link @valse

**Comment by sidharthachatterjee** [comment]
Fixed and published in `gatsby@2.10.4`

**Comment by rchrdnsh** [comment]
Hi @sidharthachatterjee! 😁

Thank you and your team for all your hard work on this issue...

buuuuuut...

it's still not quite working for me...

I ran `gatsby info`:

```bash
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.10.4 => 2.10.4
    gatsby-cli: ^2.7.2 => 2.7.2
    gatsby-image: ^2.2.3 => 2.2.3
    gatsby-mdx: ^0.6.3 => 0.6.3
    gatsby-plugin-intl: ^0.2.4 => 0.2.4
    gatsby-plugin-layout: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: ^2.2.0 => 2.2.0
    gatsby-plugin-netlify: ^2.1.0 => 2.1.0
    gatsby-plugin-offline: ^2.2.0 => 2.2.0
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^2.2.1 => 2.2.1
    gatsby-plugin-styled-components: ^3.1.0 => 3.1.0
    gatsby-plugin-twitter: ^2.1.0 => 2.1.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.0 => 2.1.0
    gatsby-source-instagram: ^0.5.0 => 0.5.0
    gatsby-transformer-remark: ^2.5.0 => 2.5.0
    gatsby-transformer-sharp: ^2.2.0 => 2.2.0
    gatsby-transformer-yaml: ^2.2.0 => 2.2.0
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```

...and deleted the cache, package-lock and npm modules, then re-installed all of them again, then ran the site, and the problem of the router not working for me is still persisting.

If you have a moment, maybe you can take a look at the repo and see if you can spot anything that I might still be doing wrong?

https://github.com/arrowgtp/alma

Also, here is the URL of the latest build pushed to Netlify:

www.alma.vacations

**Comment by kishorevarma** [comment]
I am having the same issue.  following is my gatsby info, @rchrdnsh  have you found the bug

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 47.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.29 => 2.2.37
    gatsby-plugin-canonical-urls: ^2.1.18 => 2.1.18
    gatsby-plugin-create-client-paths: 2.1.20 => 2.1.20
    gatsby-plugin-google-analytics: ^2.0.13 => 2.1.31
    gatsby-plugin-layout: ^1.0.11 => 1.1.18
    gatsby-plugin-manifest: ^2.2.23 => 2.2.34
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1
    gatsby-plugin-offline: ^3.0.16 => 3.0.30
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.18
    gatsby-plugin-sass: ^2.0.1 => 2.1.26
    gatsby-plugin-typescript: 2.1.23 => 2.1.23
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-source-prismic: ^2.3.0-alpha.3 => 2.3.0-alpha.3
  npmGlobalPackages:
    gatsby-cli: 2.8.23

**Comment by subreena** [comment]
Hi ! so I I am trying to route between pages in gatsby by using Link. It works perfectly in local host but sadly not in netlify.
The route link is My-site.com/about/ The page appears blank. It doesn't work in netlify but when I reload the page the route become My-site.com/About/ and the page content shows.

**Comment by veres7** [comment]
<POSSIBLE SOLUTION>
I was not using Gatsby but had similar problem. I switched BrowserRouter to HashRouter from "react-router-dom" and routing works as it should.
