### ISSUE TITLE
useStaticQuery with object arguments causes fragment error

### ISSUE THREAD

**Issue by patrickbenjamin1** [gatsbyjs/gatsby#16123]
## Description

useStaticQuery with object arguments in graphql from `gatsby-source-graphql` causes errors that make it look like they're somehow being parsed as fragments.

### Steps to reproduce

The following typescript causes the issue

(this is one example - every other file like this is throwing the same error)

```ts
interface IFeaturedProjectsQuery {
  projects: Project[];
  copy: {
    featured_projects_copy: {
      header: string;
      description: string;
      icon: {
        path: string;
      }[];
    };
  };
}

export const useFeaturedProjects = (): IFeaturedProjectsQuery => {
  const query = useStaticQuery<
    ICosmosQuery<
      { copy: IFeaturedProjectsQuery['copy'] },
      { projects: Project[] }
    >
  >(
    graphql`
      query useFeaturedProjectsQuery {
        cosmos {
          collections {
            projects(

             /* THIS IS THE KEY BIT - REMOVING THESE ARGUMENTS STOPS THE ERROR FROM THROWING */

              sort: { field: order, direction: ASC }
              where: { field: featured, operation: eq, value: "true" }
            ) {
              client_name
              client_brand_color
              client_logo {
                ticket
              }
              project_description_short
              project_cover_image {
                ticket
              }
              project_transparent_bg_mockup {
                ticket
              }
              project_quote {
                quote_text
                author_name
                author_position
                author_photo {
                  ticket
                }
              }
              order
              quick_details {
                detail_name
                detail_icon {
                  ticket
                }
              }
              featured
            }
          }
          pages {

           /* THIS ARGUMENT WHICH IS JUST A STRING, HOWEVER, RUNS FINE */

            copy: home(dataKey: "page") {
              featured_projects_copy {
                header
                description
                icon {
                  ticket
                }
              }
            }
          }
        }
      }
    `
  );

  return {
    projects: query.cosmos.collections.projects,
    copy: query.cosmos.pages.copy
  };
};

export default useFeaturedProjects;
```

This only causes the issue in code. In GraphiQL, the query runs fine.

Removing the object arguments from the GraphQL allows it to run perfectly fine and I can get the site running locally.

### Expected result

The site should build normally when running `gatsby develop`

### Actual result

When running `gatsby develop`, the following error appears in the console for each useStaticQuery hook with object arguments in the graphql

```bash
 ERROR #85908  GRAPHQL

There was an error in your GraphQL query:

The fragment "undefined" does not exist.

File: src/hooks/staticQueries/useFeaturedProjects.ts
```

While in the browser I get the following error

```js
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
useStaticQuery
/Users/patrickbenjamin/Git/rocketmakers/rocketmakers-website/web/.cache/gatsby-browser-entry.js:1
> 1 | import React from "react"
  2 | import PropTypes from "prop-types"
  3 | import Link, {
  4 |   withPrefix,
View compiled
useFeaturedProjects
src/hooks/staticQueries/useFeaturedProjects.ts:19
  16 | }
  17 | 
  18 | export const useFeaturedProjects = (): IFeaturedProjectsQuery => {
> 19 |   const query = useStaticQuery<
  20 |     ICosmosQuery<
  21 |       { copy: IFeaturedProjectsQuery['copy'] },
  22 |       { projects: Project[] }
View compiled
```

and while the build completes, I am unable to see the site in the browser. The components wrapped in gatsby-browser.js flash on screen before going to the error screen.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.5.0 - ~/.nodenv/shims/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nodenv/shims/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 67.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.41 => 2.13.41
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4
    gatsby-plugin-lodash: ^3.1.2 => 3.1.2
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.2
    gatsby-plugin-sass: ^2.1.3 => 2.1.3
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-source-graphql: ^2.1.3 => 2.1.3
    gatsby-source-twitter: ^1.3.4 => 1.3.4
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by pieh** [comment]
On first glance seem like this is related to enum arguments, given that failing part of query contains those, while other part you pointed out that use string arguments works fine.

Are you able to share reproduction for this? Either publicly or via DMs?

**Comment by stefanprobst** [comment]
We might want to switch `gatsby-source-graphql` to use [`graphql-tools-fork`](https://github.com/yaacovCR/graphql-tools-fork) instead of the official `graphql-tools` -- it includes my enum fix which has been open in the apollo repo without maintainer response for over four months now.

**Comment by pieh** [comment]
Oh interesting - worth try using `graphql-tools-fork`. If there are no public API changes, I'll release canary of `gatsby-source-graphql` with that.

That thing aside - if it indeed is enum problem - the error that @patrickbenjamin1 is seeing defenitely looks pretty weird. So reproduction would still be valuable to figure out why such weird error shows up.

**Comment by pieh** [comment]
@patrickbenjamin1 I released canary version of `gatsby-source-graphql` after suggestion from @stefanprobst - this is educated guess and we can't know for sure if it will help or not (or if it will cause even more problems heh) - but if you could, please try installing and checking it out:

`npm install gatsby-source-graphql@graphql-tools-fork` / `yarn add gatsby-source-graphql@graphql-tools-fork` (depending which one you use).

If it does work, I will create PR and apply those changes to stable version ( https://github.com/gatsbyjs/gatsby/commit/81089bc11749296694ac85786d42030171bee059 )

**Comment by patrickbenjamin1** [comment]
Okay nice one, I'll have a try!

If it doesn't work, I can DM you a link to the repo (it has a couple api keys in there so i'd rather not put it out publicly)

**Comment by patrickbenjamin1** [comment]
No dice unfortunately - the errors are still appearing in the same way even after a big cleanup of the cache and node_modules. 

I'll give you access to the repo on Gitlab @pieh 

It's all in the branch `hooks` 

FYI, there's likely to be tonnes of other errors if you do manage to get past these errors as the whole site is going through a huge refactor and we just changed the whole shape of the data that's coming from the CMS.

**Comment by patrickbenjamin1** [comment]
@pieh 

I've put together this really stripped back public repo for replication

https://github.com/patrickbenjamin1/gatsby-graphql-error-replication/tree/master

It has two hooks in it, one with an enum argument, and one without. The enum one causes errors in the console and in the browser, the other one does not.

**Comment by patrickbenjamin1** [comment]
Also just been testing around, this is a problem with StaticQueries in general not supporting enums. I just tried it with a StaticQuery component and got the same issue.

**Comment by stefanprobst** [comment]
i think this could be similar to #16241. have you tried making `sort` and `where` an array?

we don't show the correct error message because of #16248

this is fixed in relay upstream, our relay  fork needs https://github.com/freiksenet/relay/pull/1 to be merged and released

**Comment by patrickbenjamin1** [comment]
Aha! Yeah this has fixed it, is this something that maybe should be added to the documentation as well?

**Comment by stefanprobst** [comment]
This is actually a bug in relay: the graphql spec requires single values on list fields to be interpreted as single-value-lists. relay did not correctly check this case when there was a list-of-objecttype field. this is now fixed upstream, we need to do the same for our relay-fork. @freiksenet can we merge https://github.com/freiksenet/relay/pull/1 and release a new version?
