### ISSUE TITLE
URL with unicode characters will not load in MS Edge

### ISSUE THREAD

**Issue by davegreig** [gatsbyjs/gatsby#17556]
## Description

If a URL contains a unicode character (for example `foo.com/bår`) Gatsby will not render the page correctly in Microsoft Edge. 

### Steps to reproduce

Easiest way to do this:
1. Use the [Gatsby + Netlify CMS starter](https://www.gatsbyjs.org/starters/netlify-templates/gatsby-starter-netlify-cms/)
2. Change one of the existing markdown files to have a special character in the file name
3. Build and serve the site

Or just clone [this](https://github.com/roadwig/gastby-netlify-ms-edge-issue) repo, build and serve. The bug is displayed when accessing `http://localhost:8000/blog/2016-12-17-making-sense-of-the-scaas-new-flavor-wheél/` 

### Expected result

The page should load if accessed either directly, or via a link.

### Actual result

In MS Edge, navigation to the page results in a white screen. 
On refresh, the content flickers then disappears again. There are no console errors.
Worth noting that `<div id="___gatsby">` is empty.

![bug](https://user-images.githubusercontent.com/10669516/64706136-53b23a80-d4b1-11e9-8ad1-2d11d8b2f667.gif)

Firefox and Chrome work correctly.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.31 => 2.15.11 
    gatsby-image: ^2.0.23 => 2.2.17 
    gatsby-plugin-netlify: ^2.0.6 => 2.1.11 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.1.13 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.1.6 
    gatsby-plugin-sass: ^2.0.7 => 2.1.13 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.20 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.1.17 
    gatsby-remark-images: ^3.1.6 => 3.1.20 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.3 
    gatsby-source-filesystem: ^2.0.26 => 2.1.21 
    gatsby-transformer-remark: ^2.6.9 => 2.6.21 
    gatsby-transformer-sharp: ^2.1.9 => 2.2.13 
```
NB: I'm able to test on Edge via a VM, but can confirm that the issue exists for a deployed site accessed by a MS Edge user on a Windows machine.

**Comment by jonniebigodes** [comment]
@roadwig i've been testing it out and it seems that while chrome and firefox are "smart" enough to detect the characters in the url and resolve it, it seems that edge is not. After issuing `gatsby develop` or `gatsby build && gatsby` serve and opening up the specific post in edge in windows 10 i'm presented with the following:
![roadwig_1](https://user-images.githubusercontent.com/22988955/64736474-a1936680-d4e2-11e9-84d9-c2212fa2033c.png).
As a workaround that could play nice for all the browsers you could avoid using special characters in the filename, who will be made into the slugs.

**Comment by roadwig** [comment]
Hi @jonniebigodes, thanks for having a look so quickly. 
At first I thought it the bug was simply MS Edge being incapable of handling unicode characters in a URL, but that doesn't seem to be the case. I can navigate to something like `http://example.com/føo` in Edge and the URL will resolve correctly.

I found that a similar issue occurs with Gatsby Link components - if the `to` prop contains some special characters, then the link would not work in MS Edge (again, it's fine in Firefox, Chrome and even IE11 😱). In this case, I can wrap the value of the `to` prop with `encodeURI` and the link will work in Edge. I'm hoping for a similar fix for users that either land directly on the page, or if they should refresh the page. 

Avoiding unicode characters in the slugs might be difficult for my use case - the site is intended for a non-English audience and we would want our slugs to be meaningful for SEO reasons.

**Comment by wardpeet** [comment]
Hi @roadwig!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by roadwig** [comment]
Did you have any luck @jonniebigodes? 
I'm starting to wonder if this is really a @reach/router issue.
This might be unrelated (I'm by no means an expert), but in [this sandbox ](https://codesandbox.io/embed/reach-router-starter-v1-ljeht), any route with a special character breaks the rendering...

**Comment by jonniebigodes** [comment]
@roadwig no sorry but no...i tried a couple of things but no luck. I'm also inclined that it could a issue regarding @reach/router as well.

**Comment by roadwig** [comment]
Actually, my comment above about @reach/router might not be relevant to this discussion. If the route path is wrapped with `encodeURI` then routing works. That's the same functionality as the Gatsby Link component (ie the `to` prop needs to be encoded URI if it has special characters).

So perhaps this is still a Gatsby bug?
In Edge the `<div id="___gatsby">` is shown as empty - but that's obviously not the case when you look at the HTML. Is it possibly one of the scripts injected into the HTML by Gatsby?

**Comment by roadwig** [comment]
Hey @jonniebigodes / @wardpeet - I'm not really sure how the Gatsby team triage issues but just wondering if we should change the label on this issue (it's currently `status: awaiting author response`), or do you still need further details from me?

**Comment by jonniebigodes** [comment]
@roadwig i've just removed it, i'm going to leave in the question label.

**Comment by roadwig** [comment]
This bug is still a problem for me. I can't seem to add a `not stale` label to this issue either.

**Comment by roadwig** [comment]
This bug is not limited to the netlify starter.
See also: https://github.com/roadwig/gatsby-site
If you build and serve this site, you will see that `/påge-2` works in other browsers but not MS Edge

**Comment by ccchapman** [comment]
This issue has not been resolved.

**Comment by ardeois** [comment]
Hi !

I had the same issue on one of my project, and after some digging, I found that it's related to MS edge not handling `window.location.pathname` properly.
Other browsers will url encode this value, but MS Edge doesn't. So this bug could I think be fixed in @react/router.

See this issue for more details https://github.com/reach/router/issues/343

**Comment by j218** [comment]
@davegreig @ardeois Did you guys find a workaround this issue??

**Comment by ardeois** [comment]
@j218 not really, I've opened a PR in `react/router` but I'm still waiting feedback from the contributors.
Meanwhile our site is not working properly on Edge
Feel free to comment on https://github.com/reach/router/issues/343 and https://github.com/reach/router/pull/344

**Comment by ardeois** [comment]
@davegreig @j218 the issue on @react/router has been fixed, just update your yarn.lock to use `@reach/router@1.3.3`

This fixes the issue for me 🎉

**Comment by danabrit** [comment]
This issue has gone quiet over the last few months. Is anyone still experiencing this issue? If so, could you please give an update with a fuller description? Thank you!

**Comment by ardeois** [comment]
@danabrit Issue is fixed and could be closed. You could wait for @davegreig to comment though

**Comment by davegreig** [comment]
Sorry for the delay in my reply. I’ll test the solution tomorrow and update the issue.

**Comment by davegreig** [comment]
Can confirm this solves my issue. Thanks for the help!
