### ISSUE TITLE
Develop failure: ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by EricSong8612** [gatsbyjs/gatsby#1847]
when I add gatsby-source-contentful in plugins, I get error:
<img width="565" alt="screen shot 2017-08-17 at 4 03 32 pm" src="https://user-images.githubusercontent.com/23457015/29433518-7d81e8f2-836d-11e7-9833-68c8eec1fa7f.png">
the gatsby-config.js is like:
<img width="576" alt="screen shot 2017-08-17 at 5 01 40 pm" src="https://user-images.githubusercontent.com/23457015/29433587-c4be931e-836d-11e7-8c66-201a484f510b.png">

**Comment by KyleAMathews** [comment]
This issue should be fixed now.

**Comment by KyleAMathews** [comment]
Update to the latest version.

**Comment by whmountains** [comment]
I still have this problem after upgrading to Gatsby v1.8.16.  Tried nuking `.cache` but no change.

I started getting the error when I added an async function to my code.  Am I supposed to install the babel runtime or is this a bug in Gatsby?

**Comment by pie6k** [comment]
I've got exactly the same issue as @whmountains . I'm using gatsby with typescript.

**Comment by auser** [comment]
How did you fix it, @pie6k ?

**Comment by pie6k** [comment]
I didn't. @auser

**Comment by Jaikant** [comment]
I am facing the same error, any suggestions!

```
Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at Login.js:53
    at Login.js:65
    at Object../src/containers/Login.js (Login.js:102)
    at __webpack_require__ (bootstrap e58e01e5cf6cfda1fba5:555)
    at fn (bootstrap e58e01e5cf6cfda1fba5:86)
    at Object../src/pages/login.js (login.js:1)
    at __webpack_require__ (bootstrap e58e01e5cf6cfda1fba5:555)
    at fn (bootstrap e58e01e5cf6cfda1fba5:86)
    at Object../.cache/sync-requires.js (sync-requires.js:15)
    at __webpack_require__ (bootstrap e58e01e5cf6cfda1fba5:555)
```

**Comment by serby** [comment]
@Jaikant Your issue looks like in the browser app you've not included the babel-polyfill or regenerator-runtime

Try adding the below to `gatsby-browser.js`

```js
exports.onClientEntry = () => {
  require('babel-polyfill')
}
```

https://www.gatsbyjs.org/docs/browser-apis/
