### ISSUE TITLE
Minified React error #37 on Production only

### ISSUE THREAD

**Issue by kbariotis** [gatsbyjs/gatsby#1859]
I am getting this error on production build only and I am having trouble debugging it. Do you have any idea what my causing it or how to debug?

The error is completely random and on random pages on my site. I cant find common components that may be causing it.

Thank you 

```
Uncaught Error: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:31)
    at Object._renderNewRootComponent (ReactMount.js:310)
    at Object._renderSubtreeIntoContainer (ReactMount.js:401)
    at Object.render (ReactMount.js:422)
    at production-app.js:198
    at r (loader.js:318)
    at loader.js:337
    at loader.js:112
    at loader.js:95
    at index.json?832c:11
```

**Comment by sarneeh** [comment]
What version of Gatsby are you using? I think this issue has been resolved few days ago: #1712

**Comment by kbariotis** [comment]
@sarneeh aha! Indeed I was using an older version of Gatsby. Switched to the latest. I will let you know if that fixed the issue cause its really random. Thanks :)

**Comment by kbariotis** [comment]
@sarneeh it seems like the issue is still there, even with the latest Gatsby release. Any other idea?

**Comment by sarneeh** [comment]
@kbariotis Ok, so two questions: 
1. Show me your HTML component
2. How do you know that the issue is still there. Do you replicate it yourself from time to time?

I'm not a Gatsby contributor and I don't know what could cause the problem but I've got this issue myself and bumping the version has fixed it for me :)

**Comment by kbariotis** [comment]
@sarneeh you can find everything [on my repo](https://github.com/kbariotis/kostasbariotis.com/tree/master/src/). I am replicating from time to time. Try to load the site, navigate around and hit the refresh button on every navigation. Watch the console log.

**Comment by KyleAMathews** [comment]
What is the actual error? I.e. if you visit the react site?

**Comment by kbariotis** [comment]
@KyleAMathews are you referring [to this](https://facebook.github.io/react/docs/error-decoder.html?invariant=37)?

The error is:

> # Error Decoder
> In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.
>
> We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original text of the error.
> 
> The full text of the error you just encountered is:
>
> _registerComponent(...): Target container is not a DOM element.

**Comment by KyleAMathews** [comment]
Yes that one :-)

If you search for that error then https://github.com/gatsbyjs/gatsby/issues?utf8=✓&q=is%3Aissue%20target%20container

**Comment by kbariotis** [comment]
@KyleAMathews I see but all of these issues seem to have been resolved, so I was expecting the latest version of Gatsby to not have this issue. I am still investigating though.

**Comment by KyleAMathews** [comment]
Hmm yeah the intermittent error sounds like https://github.com/gatsbyjs/gatsby/issues/1712

**Comment by KyleAMathews** [comment]
You don't have a service worker by chance? Perhaps you're seeing old code.

**Comment by kbariotis** [comment]
Nop, no service worker. :)

**Comment by kbariotis** [comment]
Take a look on this: notice how the same error message is coming from two different traces. The highlighted line is from the second message that I clicked on `production-app.js:198`.


![screen shot 2017-08-20 at 16 36 31](https://user-images.githubusercontent.com/605742/29495324-cb33cfb6-85c5-11e7-9ae3-aa4e8a18e2c9.png)

**Comment by KyleAMathews** [comment]
Closing out old issues. Please open a new issue if you're still seeing trouble!
