### ISSUE TITLE
Can't filter on childMdx fields

### ISSUE THREAD

**Issue by cwgw** [gatsbyjs/gatsby#19357]
## Description

Queries that filter on childMdx fields return no nodes.

### Steps to reproduce

Execute a query for file nodes that includes a filter on some childMdx field.

```
query {
  allFile(
    filter: {childMdx: {frontmatter: {title: {eq: "First Post"}}}}
  ) {
    edges {
      node {
        id
      }
    }
  }
}
```

### Expected result

The query should return file nodes that match the filter.

### Actual result

The query returns nothing.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 3.7.5 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.13.50 => 2.17.10 
    gatsby-image: ^2.2.8 => 2.2.30 
    gatsby-plugin-manifest: ^2.2.4 => 2.2.26 
    gatsby-plugin-mdx: ^1.0.0 => 1.0.55 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.13 
    gatsby-plugin-sharp: ^2.2.9 => 2.2.36 
    gatsby-source-filesystem: ^2.1.8 => 2.1.35 
    gatsby-transformer-sharp: ^2.2.5 => 2.3.2 
  npmGlobalPackages:
    gatsby-cli: 2.8.8
    gatsby-dev-cli: 2.5.36

**Comment by cwgw** [comment]
Here's a [repo](https://github.com/cwgw/gatsby-issue-19357) to demonstrate.

Am I doing something wrong? I should be able to filter on child node fields, right?

<img width="947" alt="Screen Shot 2019-11-07 at 4 53 21 PM" src="https://user-images.githubusercontent.com/34384816/68440243-421ea380-017f-11ea-99b5-50bdc106adb5.png">

**Comment by LekoArts** [comment]
cc @freiksenet @vladar

**Comment by vladar** [comment]
It looks like a bug for me. But maybe we are not supposed to filter by convenience child fields. @freiksenet, can you clarify this?

The issue is that `childMdx` only exists as a graphql field, it is not a part of the node model hence can't be filtered easily via sift.

**Comment by vladar** [comment]
Should be fixed in gatsby 2.17.16

**Comment by muravitskiy** [comment]
Still does not work for me if the filter field is optional. For some reason it works from the graphql console, but not for `gatsby develop` or `gatsby build`. If field is present in all .mdx files - works as expected.
```
query {
  allFile(
    filter: {childMdx: {frontmatter: {optional_field: {eq: "Some value"}}}}
  ) {
    edges {
      node {
        id
      }
    }
  }
}
```

**Comment by muravitskiy** [comment]
For me, it works in graphql console but does not work in a page query during gatsby build. Fun fact: in develop mode if I remove filtering by child field - query obviously works but gets incorrect data, but then if I put a filter back - it works correctly.
