### ISSUE TITLE
Error: Cannot find module 'gatsby-1-config-css-modules'

### ISSUE THREAD

**Issue by m8ker** [gatsbyjs/gatsby#1961]
I'm following the Gatsby tutorial. When I run `npm run develop`, I get the above error.

**Comment by markmichon** [comment]
@m8ker There was an issue with this yesterday that *should* be resolved now. You may need to update gatsby-cli.

**Comment by m8ker** [comment]
Thanks. I ran `npm uninstall --global gatsby-cli`, then `npm install --global gatsby-cli`, but it didn't fix the issue.

**Comment by m8ker** [comment]
I started from scratch and it works. Thanks
