### ISSUE TITLE
blog: missing tag page for `100-Day-of-Gatsby`

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#20364]
## Description

missing tag `100-Day-of-Gatsby`

### Steps to reproduce

- i open the blog post ( https://www.gatsbyjs.org/blog/100days/start-blog/ )
- click on bottom on tag `100-Day-of-Gatsby`
- it opens https://www.gatsbyjs.org/blog/tags/100-Day-of-Gatsby

### Expected result

- tag page should show blog posts

### Actual result

- 404 Error

### Steps to reproduce

- i go to https://www.gatsbyjs.org/blog/tags 

### Expected result

- tags overview should show the tag `100-Day-of-Gatsby`

### Actual result

- no tag `100-Day-of-Gatsby`

## Related Issue

Related #20351

**Comment by freiksenet** [comment]
Thank you for the report!

Seems that it has been fixed now.

**Comment by muescha** [comment]
good that it is visible

only on the tags overview page (https://www.gatsbyjs.org/blog/tags) it is still missing the 100days tag

**Comment by muescha** [comment]
fixed with #20519
