### ISSUE TITLE
Navigation cache bug in JQuery crashes app

### ISSUE THREAD

**Issue by pedro-surf** [gatsbyjs/gatsby#20918]
After successfully building, this error suddenly comes in at one point:
```
TypeError: document.getElementById(...) is null
componentDidUpdate/<
project/.cache/navigation.js:173

  170 | if (document.title) {
  171 |   pageName = document.title
  172 | }
> 173 | const pageHeadings = document
  174 |   .getElementById(`gatsby-focus-wrapper`)
  175 |   .getElementsByTagName(`h1`)
  176 | if (pageHeadings && pageHeadings.length) {
```
Thank you
And I'm available to help

**Comment by freiksenet** [comment]
Hi @pedro-surf!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! :purple_heart: 

[reproduction]: https://gatsby.dev/reproduction

**Comment by Unique111** [comment]
same problem, any solution?

**Comment by aktn** [comment]
Same problem [here](https://github.com/gatsbyjs/gatsby/issues/21139)

**Comment by sidharthachatterjee** [comment]
Fixed and published in gatsby@2.19.12

Apologies for this.

**Comment by jodiedoubleday** [comment]
I'm still having this issue even though I'm using gatsby 2.19.12
It weirdly seems to occur only when using Gatsby Image.

**Comment by infomofo** [comment]
I'm also still getting this. This was on an older project that I was in the process of updating dependencies on. The dependencies that were updated were
- gatsby 2.13.60 to 2.19.18
- gatsby-image 2.2.34 to 2.2.41

It was part of a larger ncu update but since I saw this thread and it is the same issue I think this is probably the root cause.

**Comment by SamBenson** [comment]
Still having this issue - any fixes in sight? Updating doesn't appear to make any difference.
