### ISSUE TITLE
Not sending any page views: gatsby-plugin-google-gtag

### ISSUE THREAD

**Issue by muinmomin** [gatsbyjs/gatsby#21181]
## Description

For `gatsby-plugin-google-gtag` plugin, the page views are not being measured. When I deploy my personal site, in the head, I see that the config is set to: 

gtag('config', 'G-XX...', {"anonymize_ip":true,"cookie_expires":0,"send_page_view":false});

[Why is "send_page_view" being automatically set to false? ](https://github.com/gatsbyjs/gatsby/blob/561d33e2e491d3971cb2a404eec9705a5a493602/packages/gatsby-plugin-google-gtag/src/gatsby-ssr.js#L26) Not sure if this is the cause, but in the script tag, I see that that remains in there.

And in my plugins file:
{
      resolve: `gatsby-plugin-google-gtag`,
      options: {
        trackingIds: [
          "G-XX...", 
        ],
        gtagConfig: {
          anonymize_ip: true,
          cookie_expires: 0,
        },
        pluginConfig: {
          head: true,
          respectDNT: false,
        },
      }
    },

### Steps to reproduce

Included the plugin in my config file as show above.
Build and serve.
Check head script tag and see the issue, and google analytics doesn't receive any events. 

### Expected result

I should see measurements in google analytics and the ga config should not have that property.

### Actual result

Described above.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-image: ^2.2.39 => 2.2.39 
    gatsby-plugin-google-gtag: ^1.1.22 => 1.1.22 
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39 
    gatsby-plugin-offline: ^3.0.32 => 3.0.32 
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21 
    gatsby-plugin-sass: ^2.1.27 => 2.1.27 
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3 
    gatsby-source-filesystem: ^2.1.46 => 2.1.46 
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13 
  npmGlobalPackages:
    gatsby-cli: 2.8.28

**Comment by muinmomin** [comment]
Fixed.

**Comment by Badyl1g** [comment]
@muinmomin I'm having the same issue. How did you fix it?

**Comment by ardalis** [comment]
Seeing same issue. This did not fix it:
```
        gtagConfig: {
          anonymize_ip: false,
          cookie_expires: 0,
          send_page_view: true
        },
```

What worked for you, @muinmomin  ?

**Comment by Badyl1g** [comment]
@ardalis 
Ok it seems that I forgot about leaving my solution here. 
I noticed that this plugin sends the initial load event in gatsby-browser.js (in onRouteUpdate hook), so the fact that the line is commented is probably just to make sure not to fire it twice on page load

**Comment by samOpenforce** [comment]
@muinmomin 
> Fixed.

Please post your solution? I am seeing this issue also.

**Comment by holtzy** [comment]
Still looking for a solution for this issue...

**Comment by lucashfreitas** [comment]
Yeap, that stills a problem. If you use google tag manager and not google analytics, we need to send page view events on `onRouteUpdate` hooks.

**Comment by wilitp** [comment]
> ## Description
> For `gatsby-plugin-google-gtag` plugin, the page views are not being measured. When I deploy my personal site, in the head, I see that the config is set to:
> 
> gtag('config', 'G-XX...', {"anonymize_ip":true,"cookie_expires":0,"send_page_view":false});

For anyone interested in the "send_page_view: false" part: this is OK, it's the plugin avoiding duplicate tracking of page hits.
At the time of writing this, the plugin uses the `onRouteUpdate` API to send page views.

**Comment by sottom** [comment]
Any news on this issue? I'm not getting any `pageview` events firing when I click into blog posts on my page (but I do get a pageview event when I hard refresh any of the pages).
