### ISSUE TITLE
gatsby-source-contentful: how to use Gatsby Img with contentful rich text?

### ISSUE THREAD

**Issue by stephaniedavidson** [gatsbyjs/gatsby#21329]
## Summary
I'm accessing a **rich text** field from contentful (called "blurb") in a template like so:
```
const options = {
    renderNode: {
      "embedded-asset-block": node => {
         const alt = node.data.target.fields.title
         const url = node.data.target.fields.file.url
         return <img alt={alt} src={url} />
     }
}
```
in return(...)
```
{documentToReactComponents(
    props.data.contentfulWork.blurb.json,
    options
)}
```

In graphql it seems that the rich text images don't have the fluid property? How would I convert this setup to use gatsby's `<Img />` rather than regular img tag? 

Tried `return <Img src={node.data.target.fields.fluid} />` but no dice

**Comment by pieh** [comment]
I'm not sure if it's possible at the moment to use gatsby-image there :(

**Comment by connorlindsey** [comment]
This plugin might be helpful: [gatsby-remark-images-contentful](https://www.gatsbyjs.org/packages/gatsby-remark-images-contentful/?=contentful). I haven't used contentful a lot, but thought I'd share it.

**Comment by stephaniedavidson** [comment]
Ah I think this is what I need! Confused a bit though, so when I console.log out my rich text json (props.data.contentfulWork.blurb.json) I see the embedded-asset-blocks but when I look at their properties they don't have a fluid property?

**Comment by mjmaurer** [comment]
I think to properly support this, the json of the rich text would [have to be parsed here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/extend-node-type.js#L521).

For each `embedded-asset`, `embedded-block-entry`, and `embedded-inline-entry` in the json; the entry/asset could be included as a `children` of the rich text graphql node. I think this is possible, but not the most familiar with gatsby's graphql semantics

**Comment by LekoArts** [comment]
Please let us know if the mentioned plugin resolves your issue!

**Comment by mjmaurer** [comment]
Contentful's rich text format is different from Markdown. It's resolved in Gatsby GraphQL as a JSON tree. I don't think `gatsby-remark-images-contentful` is useful here.

**Comment by stephaniedavidson** [comment]
The plugin did not resolve the issue, the data from contentful rich text does not have any fluid properties so I don't think it's possible. Which is weird because media fields have that fluid property and the same assets on the contentful side are used for both. 

So I take it in conclusion with contentful and rich text you cannot use Gatsby's <Img>? Should I close this question? Thanks for your responses everyone.
