### ISSUE TITLE
Allow non-existing fields in GraphQL Queries

### ISSUE THREAD

**Issue by Unforgiven-wanda** [gatsbyjs/gatsby#2392]
Hello,
I'm using Gatsby with the Wordpress source plugin. So far so good. But the thing is I am querying fields that might or might not be there, in this case, the featured image of a post.
Here is my query:
```javascript
{
allWordpressPost(sort: { fields: [date] }) {
      edges {
        node {
          title
          excerpt
          slug
          featured_media
          better_featured_image {
            wordpress_id
            alt_text
            caption
            description
            media_type
            post
            source_url
          }
        }
      }
    }
}
```
It works well when the featured image is set, but fails miserably otherwise.
And so my question: Is there any way in GraphQL to query an optional field? To add a default value to a required field?

Thank you.

**Comment by MarcCoet** [comment]
I have/had the same problem with contentful. Here is my PR proposal #2037. It still needs to be polished.
Unfortunately it does not handle images atm because with this approach we would need a default image to fill in the field and it is not the expected behavior to have an image there if the user didn't put one. I don't know how we could set a 'falsy-like' value on an image field...
I am wondering how the graphiql interface handles this kind of stuff. If we query an unset field there it just returns null on that field.
Anyway, if someone has an idea to move this forward I am interested too.

**Comment by MarcCoet** [comment]
And the issue associated for reference: #1517

**Comment by Unforgiven-wanda** [comment]
@MarcCoet I just noticed that this particular issue makes it also impossible to publish an empty blog. Meaning if you don't have any post in your Wordpress site for example, you run into `Cannot read property 'allWordpressPost' of undefined`

We really need some way to throw a warning, instead of a full-blown error in these cases

**Comment by MarcCoet** [comment]
Totally agree but I don't know how.
I feel this is something that should be solved in gatsby core because every CMS-like source plugin is going to fall in the same traps.
Sorry @KyleAMathews but I need to mention you again here. ^^'

**Comment by sebastienfi** [comment]
We solved this by publishing a dummy post with all features set.

**Comment by Unforgiven-wanda** [comment]
This issue remains my biggest gripe with Gatsby. Simply returning `null`s to every non-existant queried field in a GraphQL query would be the best approach in my opinion, as it is trivial to check whether the field exists in React
Just a use case that I encountered this week: One of my clients' first reflex was to delete all his posts, expecting to see a no posts page, until such a time he would start filling his blog with content, and that simply broke the build process. I had all the trouble in the world to explain to him why it worked that way.

Another, more recent one had to do with the menu, where I fetch `wordpressWpApiMenusMenusItems` to display the menu he creates in the Wordpress dashboard. Again, ideally not having a menu to fetch I would not display one, instead the build process breaks, same thing when trying to fetch all menus children, something like:
```javascript
wordpressWpApiMenusMenusItems(name: { eq: "Main Menu" }) {
      items {
        wordpress_id
        title
        url
        type
        wordpress_children {
          wordpress_id
          title
          url
          attr
          target
          type
          wordpress_children {
            wordpress_id
            title
            url
            attr
            target
            type
          }
        }
      }
    }
```
If the menu does not have children, we run into the same issue.

So, I'm not sure if this is in line with Gatsby's philosophy, so maybe I'm assuming too much, but it would be much appreciated if unsuccessful GraphQL queries did not break the build, simply returning empty or null values for the fields required, then it would be up to the dev to check whether the values exist before displaying them.
What do you think of this?

**Comment by KyleAMathews** [comment]
@Unforgiven-wanda these are great examples of when this causes trouble! I have been somewhat confused why people ran into this trouble as I always build out my sites *while* adding content so don't ever have the problem of wanting to write a query against something that doesn't yet exist.

Thinking about this some more — I think it could be possible to turn what's now a build error into a warning. @jquense any thoughts on this that come to mind?

@Unforgiven-wanda would you like to investigate a possible solution to this? We use the Relay compiler for validating queries and we'd either need to somehow lower the warning level or catch its errors and not exit when it's a query that includes fields that don't exist.

**Comment by jquense** [comment]
Unfortunately there isn't really a good way to silence this sort of thing, since it's a hard error in GraphQL, even if you could tho you'd lose the validation for cases were you do want it, e.g. notification you are trying to query some field you spelt wrong or something. I agree that is can be frustrating and annoying in the development, but this is a hard constraint of how graphql works, it can _only_ query stuff that is defined in the type system. 

Ultimately the issue here is that if you only infer the schema from the input data, you are necessarily constrained to what the data contains. There isn't any way to tell graphql to just return null or something for fields that don't exist, because it needs to know a a lot of info _waaay_ before that to even try and resolve that field. You also can't work backwards from the query and do inference at that point because queries don't contain enough info to do inference (e.g. you can't distinguish a List from an Object)

In terms of what Gatsby can do, the API's for handling this already exist luckily, you need to extend the graphql types manually and specify which fields you always want to exist. We might be able to make that a bit friendly for quickly specifying additional fields, but honestly, defining GQL schema is verbose and time consuming sort of inherently. (note Apollo Launchpad [has a neat way of defining schemas quickly](https://launchpad.graphql.com/pjwnq05l0))

**Comment by Unforgiven-wanda** [comment]
@KyleAMathews Of course. i'll do my utmost to resolve this issue, and if I am successful, I'll be sure to put it a pull request
I'll be closing this issue then, since as demonstrated by @jquense there is no obvious solution for now.
Thank you all.

**Comment by sebastienfi** [comment]
This also looks promising https://github.com/marmelab/graphql-schema-from-json

**Comment by diegolamanno** [comment]
@jquense I am trying to follow your recommendation to extend graphql types manually. However, I am running in some issues that I would appreciate your input.
1) I am using `setFieldsOnGraphQLNodeType` very similar like some of the *gatsby-transform* plugins do. Am I in the right path or that's not the gatsby API you were referring to?

2) So far I have been able to add more types using ☝️ that API. But I haven't found a way to setup a default value for a UnionTypes without completely overwriting the ones coming from the API,

I hope this makes any sense, thanks

**Comment by sedubois** [comment]
> defining GQL schema is verbose and time consuming sort of inherently

How about the kind of GraphQL IDL syntax like in Graphcool GraphQL-up? https://github.com/graphcool/graphql-up
(NB: I never actually built a GraphQL backend myself and am just planning to use Graphcool, Apollo, Gatsby where needed.)

**Comment by daniel-simpson** [comment]
Just throwing another idea in the ring.  We could have the graphql schema be generated off of (or affected by) the Content Management API?  e.g:
* https://api.contentful.com/spaces/{space_id}/content_types/?access_token={access_token}

Using this API alone to generate graphql schemas would be problematic as it would make it a lot harder using the JSON object type in Contentful (there would be no way to map properties from inside JSON objects), but we could potentially check that nullable fields from that call above exist, and if not then add graphql nullable fields to each type definition at schema build time?

**Comment by hubertron** [comment]
Hey Kyle - We are running into this issue as well. It's preventing build of more modular layouts that have varying content but one template.

**Comment by m-allanson** [comment]
@hubertron there's some great work happening at #3344 to fix these 'missing field' errors.

**Comment by Kikobeats** [comment]
@Unforgiven-wanda how did you resolve that?

**Comment by Unforgiven-wanda** [comment]
@Kikobeats Unfortunately no. For my personal projects I keep a hidden page with all fields to circumvent this issue. However I had to move my clients projects to React-static (a decent alternative to Gatsby, although somewhat inferior imho) as I could not explain to them why it worked this way and the build process kept breaking because someone would either delete the hidden page or mess with it.

**Comment by Kikobeats** [comment]
The only thing necessary is to extend the GraphQL schema for the add `Nullable` over the value

**Comment by Unforgiven-wanda** [comment]
@Kikobeats I wasn't aware of that as it's been some time since I've used Gatsby.
Thank you for the info.

**Comment by Arztpraxis-Schulzendorf** [comment]
@Kikobeats Could you explain how to do this or provide a link that explains it?

**Comment by Kikobeats** [comment]
Unfortunately I didn't find how to 😢

**Comment by LouiseReid** [comment]
I'm running into this issue with Gridsome and GraphQL and it seems ridiculous that you can't delete the last entry in the collection without the build failing.  Surely this is a massive use case?

**Comment by kuworking** [comment]
This is indeed problematic:
I'm re-using a `core theme` to be able to re-use it with many `child themes`, everything around the idea of writing posts in `mdx`. 

__This is an expected use case I would say__. Then now, with my __FORTH__ `child theme` I want to expand the `mdx` `frontmatter` post files I was using so far

So until now I was using a `frontmatter` like

```
---
date: 2019.05.16
title: 'hey world'
tags: general
snippet: 'hey snippet'
abstract: 'first post'
---
```

which was processed by the `core theme`

Now with the __FORTH__ `child theme` I wanted to add another field, the `type`

```
---
type: 'javascript'
date: 2019.05.16
title: 'hey world'
tags: general
snippet: 'hey snippet'
abstract: 'first post'
---
```

So in the `core theme` I've updated the `query` to

```
          frontmatter {
            type
            date
            title
            snippet
            abstract
          }
```

And of course, this causes an error with my __FIRST__ theme, since `mdx` files there don't have the new field.

The only workaround now is to add an empty `type` field in all the posts of __all__ the previous `mdx` posts, something I can only do if I own these sites.

Is this like this? Isn't there anything I can do apart from what I've said?

[NOTE]: As a curiously, if I add the new `type` field __only__ in the two last posts, it seems to work (I see the site working with `gatsby develop`)

**Comment by Elementrat** [comment]
Ran into this one today. Would be great if builds with queries on empty fields continued, simply returning null where appropriate. My scenario is the same as @Unforgiven-wanda, I have a featured image that I don't necessarily want every post to have. As it is now, my understanding is that I'll have to put dummy data in place in my CMS, and do client-side checks for the "dummy value"

**Comment by giacomoalonzi** [comment]
Any solution found? I'm experiencing the same issue with ACF if any repeater is empty.

**Comment by devpascoe** [comment]
I'm using Contentful for site data. Similar issue, an optional short text field, if not set to required and no text entered then querying for the now missing field breaks.
Anyone reading this does Contentful have a default value setting i'm not aware of??
Regardless it would be amazing if:
- value could return null (but understand the by design issues mentioned above)
- we had an option to inherit and override the Query fields and therefore specify a default value
- manually define all the Query fields as above
There was some mention about overriding with setFieldsOnGraphQLNodeType - can some kind person point me in the right direction where i might be able to manually define the nodes (bonus points for something specific to Contentful)?

ta ❤️

**Comment by tweetzal** [comment]
@KyleAMathews  Just thought I'd let everyone know aswell that we are experiencing the same issue here in London, UK - using gatsby-source-wordpress

I have 700 pages populated from a content migration.

I added 4 new custom fields to pages in wordpress after 300 pages where populated. 

I now have 300 pages without the 4 new fields and 400 pages with the 4 new fields, and I need this data to run logic for the primary navigation/ menu.

Any suggestions or work arounds we can use.

?

**Comment by Ozerich** [comment]
@tweetzal, next code can help you

```
if (!function_exists('acf_nullify_empty')) {
    function acf_nullify_empty($value, $post_id, $field) {
        if (empty($value)) {
            return null;
        }
        return $value;
    }
}

add_filter('acf/format_value', 'acf_nullify_empty', 100, 3);
```

**Comment by giacomoalonzi** [comment]
I solved with a resolver on gatsby
gatsby-node.js

```javascript
exports.createResolvers = ({ createResolvers, schema }) => {
  const resolvers = {
    wordpress__PAGEAcfHero_text: {
      list_of_words: {
        resolve(source, args, context, info) {
          if (!source.list_of_words) {
            return info.originalResolver(
              {
                ...source,
                list_of_words: []
              },
              args,
              context,
              info
            )
          } else {
            return info.originalResolver(source, args, context, info)
          }
        },
      },
    },
    wordpress__PAGEAcfMember: {
      socials: {
        resolve(source, args, context, info) {
          if (!source.socials) {
            return info.originalResolver(
              {
                ...source,
                socials: []
              },
              args,
              context,
              info
            )
          } else {
            return info.originalResolver(source, args, context, info)
          }
        },
      },
    }
  }
  createResolvers(resolvers)
}
```

**Comment by tweetzal** [comment]
Thanks guys. Much appreciated

**Comment by robmarshall** [comment]
> I solved with a resolver on gatsby
> gatsby-node.js
> 
> ```js
> exports.createResolvers = ({ createResolvers, schema }) => {
>   const resolvers = {
>     wordpress__PAGEAcfHero_text: {
>       list_of_words: {
>         resolve(source, args, context, info) {
>           if (!source.list_of_words) {
>             return info.originalResolver(
>               {
>                 ...source,
>                 list_of_words: []
>               },
>               args,
>               context,
>               info
>             )
>           } else {
>             return info.originalResolver(source, args, context, info)
>           }
>         },
>       },
>     },
>     wordpress__PAGEAcfMember: {
>       socials: {
>         resolve(source, args, context, info) {
>           if (!source.socials) {
>             return info.originalResolver(
>               {
>                 ...source,
>                 socials: []
>               },
>               args,
>               context,
>               info
>             )
>           } else {
>             return info.originalResolver(source, args, context, info)
>           }
>         },
>       },
>     }
>   }
>   createResolvers(resolvers)
> }
> ```

Would this mean creating a resolver for each ACF field? I am working on something that uses a hell of a lot of potentially empty fields.

**Comment by Glinkis** [comment]
I just ran into this very issue with the Contentful source plugin. I have a lot of optional fields, and potentially empty content types.

**Comment by kimbaudi** [comment]
I'm also having this issue when migrating my Jekyll site to GatsbyJS. Wish GraphQL wasn't so strict. In fact, it would be great if there was a config option that would allow GraphQL to just simply warn instead of throwing a build time error.

**Comment by hidanielle** [comment]
Running into this issue while using Gatsby and Kentico Cloud. Can't seem to get it working with the createResolver solution. Has anyone else here had any luck since?

**Comment by robmarshall** [comment]
I found writing out an entire schema (with correct values - 0 for int, false for bool, ect), and then merging entities over that worked. Bit of a long way round.

**Comment by ttstauss** [comment]
> I just ran into this very issue with the Contentful source plugin. I have a lot of optional fields, and potentially empty content types.

I'm in the same boat.

**Comment by briangonzalezmia** [comment]
I had the same problem and solved it with the following solution for my nested fields from the Gatsby site:

`exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }
    type Frontmatter {
      tags: [String!]!
    }
  `
  createTypes(typeDefs)
}`

[https://www.gatsbyjs.org/docs/schema-customization/#nested-types](url)

Hope this helps someone out there!

**Comment by briangonzalezmia** [comment]
I was able to use the following from the Gatsby Site to take care of the nested nullable:

``
exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type MarkdownRemark implements Node {
      frontmatter: Frontmatter
    }
    type Frontmatter {
      tags: [String!]!
    }
  `
  createTypes(typeDefs)
}
``
*** Don't forget to restart the dev server to see the results***

Ref: https://www.gatsbyjs.org/docs/schema-customization/#nested-types

**Comment by anonimoconiglio** [comment]
> I was able to use the following from the Gatsby Site to take care of the nested nullable:
> 
> ```
> exports.createSchemaCustomization = ({ actions }) => {
>   const { createTypes } = actions
>   const typeDefs = `
>     type MarkdownRemark implements Node {
>       frontmatter: Frontmatter
>     }
>     type Frontmatter {
>       tags: [String!]!
>     }
>   `
>   createTypes(typeDefs)
> }
> ```

Is this snippet of code complementary to the rest of gatsby-node.js? 
You added this before or after the exports.createPages module?

**Comment by bowenac** [comment]
Was having the same issue pulling in WordPress posts that have optional fields. I expected they would just return null if they didn't exist not blow up the whole query... that really puts a damper on things. 

Seems pretty common to have optional fields. Will keep looking around for a solution, but having to create a schema for every possible optional field seems more like a band aid fix.

@Ozerich thanks for the solution, that worked.

**Comment by hades200082** [comment]
Same issue here with Contentful.

Is it possible to extend the graphQL interface to allow specifying of a default value on a per-field basis such that if the field doesn't exist it will fill with the default specified in the query instead of failing the build?

**Comment by Ricky-NSW** [comment]
@benrobertsonio You provided some email support for me on April 2nd regarding the same issue (I think).
I have the Contentful plugin pulling in content. One content item in Contentful was missing data which was breaking the build with a "Compile Error" and you said a "Safety Check" would fix it - by adding a "?" in the data request, like this (notice the ?):

**Doesnt work:** biography.mediaApprovedQuote.childMarkdownRemark.html
**DOES work:** biography.mediaApprovedQuote?.childMarkdownRemark.html

When a Content Item is missing that data it is left blank.

Could this be applied elsewhere?
I haven't been able to find any more information on this technique. Ben do you know where we can learn more about this as a possible fix?

Thanks (AGAIN).

**Comment by collegewap** [comment]
I had the same problem when using [staticman](https://github.com/eduardoboucas/staticman) comments and had an optional field "replyFor"

I have added the following section in gatsy-node.js and it fixed the issue

```js

exports.createSchemaCustomization = ({ actions }) => {
  const { createTypes } = actions
  const typeDefs = `
    type CommentsYaml implements Node {
      replyFor: String
    }
  `
  createTypes(typeDefs)
}
```

**Comment by bughishor** [comment]
> I had the same problem when using [staticman](https://github.com/eduardoboucas/staticman) comments and had an optional field "replyFor"
> 
> I have added the following section in gatsy-node.js and it fixed the issue
> 
> ```js
> exports.createSchemaCustomization = ({ actions }) => {
>   const { createTypes } = actions
>   const typeDefs = `
>     type CommentsYaml implements Node {
>       replyFor: String
>     }
>   `
>   createTypes(typeDefs)
> }
> ```
> 
> [Explicitly defining data types](https://www.gatsbyjs.org/docs/schema-customization/#explicitly-defining-data-types)

I can confirm that the same approach works with Strapi (e.g type StrapiElement).

**Comment by Bowenf3** [comment]
https://www.npmjs.com/package/gatsby-plugin-contentful-optional-fields - for all those of you who still hitting on this issue in 2021! - Not my work thanks to Tim Ziegel!

**Comment by Petermhen** [comment]
> I had the same problem when using [staticman](https://github.com/eduardoboucas/staticman) comments and had an optional field "replyFor"
> 
> I have added the following section in gatsy-node.js and it fixed the issue
> 
> ```js
> exports.createSchemaCustomization = ({ actions }) => {
>   const { createTypes } = actions
>   const typeDefs = `
>     type CommentsYaml implements Node {
>       replyFor: String
>     }
>   `
>   createTypes(typeDefs)
> }
> ```
> 
> [Explicitly defining data types](https://www.gatsbyjs.org/docs/schema-customization/#explicitly-defining-data-types)

Was getting this issue in gatsby-source-wordpress while querying coupons. This answer along with the answer at following link helped me resolve it https://stackoverflow.com/questions/60289062/allow-optional-graphql-data-in-gatsby
