### ISSUE TITLE
clicks on named anchors trigger a click event

### ISSUE THREAD

**Issue by ThePeach** [gatsbyjs/gatsby#2414]
I've got a named link in a page that is correctly rendered as `<a name="section">Section</a>`.

If I try to click on it, it will try to open a page `/null`, and it seems there's an attached click event to it.

currently using gatsby 1.9.32 and node 8.4.0 (let me know if you need more info)

**Comment by KyleAMathews** [comment]
This should be fixed and we'd take a PR for it but FYI, using `<a name="something">` isn't valid HTML5 https://stackoverflow.com/questions/484719/html-anchors-with-name-or-id

Using `<a id="something">` will work.

**Comment by ThePeach** [comment]
hi @KyleAMathews thanks for your reply.
Agreed about the attribute, although the problem still stands.

**Comment by KyleAMathews** [comment]
Right, happy to take a PR to gatsby-link solving the issue.

**Comment by jmoujaes** [comment]
I'd like to work this bug if nobody else is.
@ThePeach how can I reproduce this behavior?

**Comment by ThePeach** [comment]
@jmoujaes thank you for picking this one up, unfortunately I'm not working on that project anymore, but IIRC I had a plain `<a id="anchor">Anchor</a>` in the markdown, and in the generated page clicking on it will trigger a click event. As simple as that.

**Comment by jmoujaes** [comment]
@ThePeach thanks for the additional detail!

I can't seem to reproduce with gatsby version 1.9.209

I add a link to my index.js like so
    `<a id="test">Is this null?</a>`
But it is not clickable and does not open a page /null

**Comment by m-allanson** [comment]
@jmoujaes In @ThePeach's first example the link uses a `name` attribute instead of an `id` attribute. Does that cause the error for you? `<a name="section">Section</a>`

**Comment by ThePeach** [comment]
@jmoujaes please consider that the link was in a `.md` file that was parsed into HTML, so I don't know if that is contributing at all.
Secondly, the anchor was in an second level heading (`##`), again, no idea if that contributed at all...

**Comment by jmoujaes** [comment]
@m-allanson good catch, thanks.
@ThePeach gotcha, thanks. I set up a new site with the gastby-starter-blog starter. Now I create an index.md file in one of my pages with the following:
```
title: Hello Again
date: "2018-03-01T22:12:03.284Z"
---

Hello, [Is this /null?](#section)

## Section <a name="section"></a>
```
The behavior I see is "Is this /null" renders on the page as a link, and when I click it it takes me to the Section header.

I am using Firefox 58.0.2

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
