### ISSUE TITLE
Gatsby build Error: "window" is not available during server side rendering

### ISSUE THREAD

**Issue by Prabhakar96-dev** [gatsbyjs/gatsby#25092]
I have created an application and successfully integrated with MSAL to authenticate users using Azure AD.
**gatsby develop** working fine.
  **gatsby build**  throwing an exception.

Before integrated with MSAL both **build** and **develop** commands worked When I integrated with MSAL throwing an exception.
 Exception is **"window" is not available during server side rendering**
Below is the error image
![Capture](https://user-images.githubusercontent.com/57832928/85013188-cad3d800-b181-11ea-984c-40f85cc5f471.JPG)

**Comment by LekoArts** [comment]
Thank you for opening this!

The error message prompts you to visit: https://www.gatsbyjs.org/docs/debugging-html-builds/
The page explains why you see the error and how you can resolve it. As per https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1639 the library you mentioned uses elements from the `window` object and therefore the SSR doesn't work with those. So when importing contents of those packages you need to check for the existence of `window` first.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by Prabhakar96-dev** [comment]
@LekoArts  Thank you , I tried with you answer. I created **gatsby-node.js** 

![Capture3](https://user-images.githubusercontent.com/57832928/85022179-93205c80-b190-11ea-8485-36dabb1922f1.JPG)

And below is my JS where I'm using msal. 

![Capture1](https://user-images.githubusercontent.com/57832928/85021930-2c02a800-b190-11ea-8e81-2243feae8b14.JPG)

After these changes I'm getting below exception.

**WebpackError: TypeError: msal__WEBPACK_IMPORTED_MODULE_0__.UserAgentApplication is not a constructor**

**Comment by luke-m** [comment]
The problem I have with this gatsby behaviour is that the error doesn't point to the offending file, let alone line where the faulty window call is loocated. I often find myself scanning my project and repeating the build command until I have fixed it. Is it technically not doable to point out the specific location in the code or will it be implemented in the future? @LekoArts

**Comment by Freysi21** [comment]
Your gonna have to call the UserAgentApplication constructor within a componentDidMount function.

**Comment by baemaxxssu** [comment]
> Thank you for opening this!
> 
> The error message prompts you to visit: https://www.gatsbyjs.org/docs/debugging-html-builds/ The page explains why you see the error and how you can resolve it. As per [AzureAD/microsoft-authentication-library-for-js#1639](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1639) the library you mentioned uses elements from the `window` object and therefore the SSR doesn't work with those. So when importing contents of those packages you need to check for the existence of `window` first.
> 
> We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

I still receive the error. I already wrapped with `useEffect`
