### ISSUE TITLE
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by talatkuyuk** [gatsbyjs/gatsby#25427]
## Description

I am working on gatsby with strapi.
I receive that message when I run develop
(node:43092) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### Steps to reproduce
The program fetchs all apis from strapi, no problem, but the error message appears in this context:

`info Starting to fetch data from Strapi - http://localhost:1337/jobs?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/projects?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/blogs?_limit=1000
info Starting to fetch data from Strapi - http://localhost:1337/about?_limit=1000

 ERROR 

(node:43092) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

success Fetched Strapi Data - 0.272s
success source and transform nodes - 0.406s`

### Expected result

Expected no error

### Actual result

The program works correctly, fetching data from strapi. But, while "npm run develop", the error message appears:
(node:43092) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### Environment
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0 
    gatsby-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0 
    gatsby-plugin-sitemap: ^2.4.2 => 2.4.2 
    gatsby-source-filesystem: ^2.3.0 => 2.3.0 
    gatsby-source-strapi: 0.0.12 => 0.0.12 
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.51

**Comment by graysonhicks** [comment]
I believe this is a duplicate of #20529 and #18433 regarding an older version of the `got` package that is required by `gatsby-source-filesystem`.  

`gatsby-source-strapi` looks be using version `1.5.39` of `gatsby-source-filesystem` ([package.json](https://github.com/strapi/gatsby-source-strapi/blob/master/package.json#L42)).  The latest version of `gatsby-source-filesystem` is `2.3.14`.  

I believe bumping that depending in `gatsby-source-strapi` will remove the warning.

**Comment by vladar** [comment]
Closing this as it must be fixed in the upstream dependency. I suggest you open an issue (or better a PR) in the https://github.com/strapi/gatsby-source-strapi with version bump of the `gatsby-source-filesystem`.

**Comment by cbandara** [comment]
"gatsby-source-filesystem": "^2.3.14",
    "gatsby-source-strapi": "0.0.12",

I have updated my package.json and ran npm install but I still encounter this error
