### ISSUE TITLE
Quickstart fails with 'Multiple "root" queries found.'

### ISSUE THREAD

**Issue by paulhickman-a365** [gatsbyjs/gatsby#25622]
## Description

Following the instructions at https://www.gatsbyjs.org/docs/quick-start/ when I start the development server and browse to http://localhost:8000 I get an error page.

There are also warnings about case sensitivity in filenames.

### Steps to reproduce

npm install -g gatsby-cli
gatsby new gatsby-site
cd gatsby-site
gatsby develop

### Expected result

Show some sort of starter site, I assume.

### Actual result

Console showed the following:

````
$ gatsby develop
success open and validate gatsby-configs - 0.027s
success load plugins - 1.550s
success onPreInit - 0.011s
success initialize cache - 0.011s
success copy gatsby files - 0.119s
success onPreBootstrap - 0.011s
success createSchemaCustomization - 0.006s
success source and transform nodes - 0.069s
success building schema - 0.373s
success createPages - 0.001s
warn The plugin "dev-404-page" created a page with a component path that doesn't match the casing of
 the actual file. This may work locally, but will break on systems which are case-sensitive, e.g.
most CI/CD pipelines.

page.component:     "C:/src/gatsby-site/.cache/dev-404-page.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match
 the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "C:/src/gatsby-site/src/pages/404.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match
 the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "C:/src/gatsby-site/src/pages/index.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match
 the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "C:/src/gatsby-site/src/pages/page-2.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match
 the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "C:/src/gatsby-site/src/pages/using-typescript.tsx"
success createPagesStatefully - 0.131s
success updating schema - 0.034s
success onPreExtractQueries - 0.001s

 ERROR #85910  GRAPHQL

Multiple "root" queries found: "cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070" and "cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070".
Only the first ("cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070") will be registered.

Instead of:

1 | query cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070 {
2 |   site {
3 |     #...
4 |   }
5 | }
6 |
7 | query cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070 {
8 |   site {
9 |     #...
10 |   }
11 | }

Do:

1 | query cSrcgatsbySitesrcpagesusingTypescriptTsx2907560070AndCSrcgatsbySitesrcpagesusingTypescriptTsx2907560070 {
2 |   site {
3 |     #...
4 |   }
5 |   site {
6 |     #...
7 |   }
8 | }

This can happen when you use two page/static queries in one file. Please combine those into one query.
If you're defining multiple components (each with a static query) in one file, you'll need to move each component to its own file.

File: src\pages\using-typescript.tsx

See our docs page for more info on this error: https://www.gatsbyjs.org/docs/graphql/

````

When browsing to http://localhost:8000, the browser showed the same graphql message that was in the console.

### Environment

  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-image: ^2.4.9 => 2.4.9 
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14 
    gatsby-plugin-offline: ^3.2.13 => 3.2.13 
    gatsby-plugin-react-helmet: ^3.3.6 => 3.3.6 
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14 
    gatsby-source-filesystem: ^2.3.14 => 2.3.14 
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.59

**Comment by pieh** [comment]
Can you run `cmd /C "set GATSBY_LOGGER=yurnalist && gatsby build"` as well as output of `cd` (no args, this should just show current working directory)? It seems like the warnings are cut a bit and they are missing more information that should be there. This will not fix the issue, but hopefully would show some.

Because of windows being very forgiving when it comes to path casing it actually cause problems, because using path to file as lookup key is in some case unreliable if path is not normalized in some way in every place :(

**Comment by vladar** [comment]
We had a similar issue in the past: #19863 (it must be solved now)

Still, can you also share a path in your terminal when you run `gatsby develop`? The issue above was reproducible with a lowercase drive letter in the terminal, i.e.:

This failed:
```
cd c:\dev\something
gatsby develop
```

This worked (note the capital `C:\` in a drive):
```
cd C:\dev\something
gatsby develop
```

**Comment by ascorbic** [comment]
Hi. I'm going to close this now as we've not heard back from you. If @vladar 's suggestion didn't fix it, can you post the info requested by @pieh and reopen this. Thanks.

**Comment by anikets** [comment]
@paulhickman-a365 In `pages` directory, do you have two files with same name and different extensions? e.g. *index.js* and *index.tsx*. Try removing the .js file.

I was getting same error as yours and it was fixed when I removed the *index.js* file which was just a non-typescript copy of *index.tsx*.
