### ISSUE TITLE
[gatsby-source-contentful] Gatsby fails to connect to other Contentful environments than master

### ISSUE THREAD

**Issue by jankohofmann** [gatsbyjs/gatsby#26909]
## Description

For `gatsby-source-contentful` version 2.1.45 and newer, when trying to access content from a Contentful space in another environment than `master` (for instance `development`) with an access token that is only allowed for this environment, but not also for `master`, Gatsby fails to connect with the message _'Accessing your Contentful space failed.'_.

It connects successfully if the access token also allows access to the `master` environment, but I need to have individual access tokens for each environment.
This behavior only occurs since `gatsby-source-contentful` version 2.1.45, including the most recent version 2.3.46. For older versions up to 2.1.44, it works fine.

### Steps to reproduce

- create Contentful space with two environments, e.g. `master` and `development`
- create an access token with only access to the `development` environment
- install the most recent versions of `gatsby` and `gatsby-source-contentful`
- setup `gatsby-source-contentful` to connect to the `development` environment with the access token
- run `gatsby develop`

### Expected result

Gatsby runs correctly.

### Actual result

With `gatsby-source-contentful` version 2.1.45 and newer, it crashes with this error message:
```
Accessing your Contentful space failed.
Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.

Used options:
spaceId: "*********dbd"
accessToken: "***************************************SnLg"
environment: "development"
host: "cdn.contentful.com"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
pageLimit (default value): 100
useNameForId (default value): true

not finished source and transform nodes - 0.422s
error Command failed with exit code 1.
```

### Environment
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.60 => 2.24.60
    gatsby-plugin-manifest: ^2.0.19 => 2.3.3
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-react-helmet: ^3.0.7 => 3.2.1
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2
    gatsby-plugin-sass: ^2.0.10 => 2.2.1
    gatsby-source-contentful: ^2.3.46 => 2.3.46
```

**Comment by vladar** [comment]
CC @axe312ger

**Comment by axe312ger** [comment]
The plugin changed the way it caches sync API data. Unfortunately that broke the support for using multiple spaces.

We will have a look into this, it might be not too much effort.

**Comment by axe312ger** [comment]
@jankohofmann Did you fix the issue? Just checked, the way the plugin uses the SDK should support environments.

This issue usually is due some wrong environment variable or some copy & paste mix up.


If you still running into this let me know, then I'll have a closer look.

**Comment by axe312ger** [comment]
I found an internal ticket confirming this issue.

Looks like for now your access token needs to have access to master environment, even when content is loaded from a different environment.

I will keep u posted.

**Comment by jankohofmann** [comment]
@axe312ger yes, I use that as a workaround and have temporarily granted access to the master env for the token.

**Comment by Phoen1x84** [comment]
I ran into this issue last week and used the suggested workaround for the time being. From what I can see the fetch api is just missing the environment with a param or default to master in the url should fix the issue.

https://github.com/gatsbyjs/gatsby/blob/db05fe28aa2dcb4eccc780e6cb433c922978f83b/packages/gatsby-source-contentful/src/gatsby-node.js#L29-L48

**Comment by axe312ger** [comment]
So, I investigated, this is how it is:

Due to restrictions in the Contentful SDK, we have to have to access to `master` environment to probably load the space/environment locales.


I'll create a PR that adjust the readme and give proper feedback in case connecting to Contentful fails

@Phoen1x84 you referenced old source code. The environment is already properly used in this test function.

**Comment by axe312ger** [comment]
This was fixed in `v4.7.0`. Closing

**Comment by Chibionos** [comment]
still happening on version : 5.11.0

Accessing your Contentful space failed: NotFound

The resource could not be found.

Request ID: 34fbfdcd-d124-4104-9da4-0895eb95e27a

Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.

Used options:
accessToken: "***************************************ZiwA"
spaceId: "*********lcm"
environment: "apollo"
host: "cdn.contentful.com"
downloadLocal: false
localeFilter: [Function]
forceFullSync: false
pageLimit: 1000
assetDownloadWorkers: 50
useNameForId: true
contentfulClientConfig: {}
enableTags (default value): false

not finished source and transform nodes - 0.216s

**Comment by axe312ger** [comment]
@chibionos please check if your access token has access to your `apollo` environment
