### ISSUE TITLE
navigate() function load the url but the page is not refreshed on mobile

### ISSUE THREAD

**Issue by developer0116** [gatsbyjs/gatsby#27020]
the current url is "/abc/?tag=a" and I navigated it to "abc/?tag=b".
But the url on the browser is changed, but the page is not refreshed on mobile.

Look forward to your support.

Best

**Comment by sidharthachatterjee** [comment]
@developer0116 This doesn't sound Gatsby specific. Could you provide more details or possibly a [minimal reproduction](https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case)?

**Comment by hayatae** [comment]
This appears to be a regression somewhere between gatsby 2.24.63 and 2.24.73 dealing with navigation changing only the search parameter.

On version 63, calling `navigate('?p=42', { replace: true })` updates the URL search parameter and causes a component re-render. Inside the render, accessing either `location.search` (via gatsby's passed in location) or `window.location.search` shows the expected value of `?p=42`

After updating to version 73, making that exact same call in the exact same way (no code changes at all), the page re-renders, but accessing location.search (via either method) returns the *previous* URL search value, not the newly updated one. Further calls to navigate continue to update the URL in the browser, but no further component re-renders are invoked. I'll try to put together a minimal reproduction for this.

**Comment by hayatae** [comment]
Minimal reproduction repo:
https://github.com/hayatae/gatsby-search-param-bug

Steps to reproduce:
1. Run `npm run develop`
2. Open the page, click on the buttons to change the search param - observe no updates

See it work in an older version of gatsby:
1. Run `npm install gatsby@2.24.63`
2. Run `npm run develop`
3. Open the page, click the buttons, see everything update as expected when the URL changes

**Comment by doscio** [comment]
I have the same issue when i recall the same page with a different state: `navigate('/page', { state: { newState }})`.

The problem appear after upgrading `gatsby` to version `2.24.70`, older versions work without problems.

**Comment by wardpeet** [comment]
Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by doscio** [comment]
Hi @wardpeet, i've created a minimal reproduction that show the problem. 

https://github.com/doscio/gatsby-navigate-issue 

The index page has a button that navigate to `/counter` page. On that page, everytime the button `Increase counter` is pressed, 
the counter should increase it's value, but this is not appening on gatsby version `2.24.79`.

Versions prior to `2.24.70` works without problem:

1. Run `npm install gatsby@2.24.69`
2. Run `gatsby develop`

Everytime I click `Increase counter` the counter is updating correctly.

**Comment by hayatae** [comment]
@doscio @wardpeet I've already created a minimal reproduction and posted it in the comments above: https://github.com/gatsbyjs/gatsby/issues/27020#issuecomment-706850931

You can very easily modify this same reproduction to reproduce the same issue with state not updating. Basically, no `navigate` functions work correctly for refreshing any query or state params on the same route after version `2.24.70`.

**Comment by LekoArts** [comment]
Fixed by https://github.com/gatsbyjs/gatsby/pull/27594

Please install `gatsby@2.24.85` and it should work again.

**Comment by AidenFaulconer** [comment]
This issue is still not fixed, in my app when I programmatically call navigate() from my global store, it updates the URL but does nothing to update the page, it only updates the page when I manually refresh it
