### ISSUE TITLE
Can no longer run gatsby develop

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#27458]
## Description

I can no longer run gatsby develop after updating the CLI.

### Steps to reproduce

run `gatsby develop`

### Expected result

Should run develop fine
 
### Actual result

```
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve 'react/jsx-runtime.js' in '/Users/joetaylor/Documents/www/joebentaylor/.cache'

If you're trying to use a package make sure that 'react/jsx-runtime.js' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache/develop-static-entry.js
```

### Environment

```

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.19.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 86.0.4240.80
    Edge: 83.0.478.54
    Firefox: 80.0.1
    Safari: 14.0
  npmGlobalPackages:
    gatsby-cli: 2.12.107
    gatsby: 2.24.77

```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ttstauss** [comment]
Facing the same issue.

**Comment by i-bsd** [comment]
Can confirm.

Same problem.

**Comment by wardpeet** [comment]
Do you still have this with the latest gatsby? Try removing node_modules, package-lock.json and try installing again.

**Comment by joebentaylor1995** [comment]
@wardpeet Tried that several times with no luck, ill try your option @ttstauss

**Comment by i-bsd** [comment]
I think it's an issue with React (jsx-transform): https://github.com/facebook/react/issues/20036

**Comment by joebentaylor1995** [comment]
Out of curiosity. @ttstauss @i-bsd do you have the Preact plugin installed?

**Comment by joebentaylor1995** [comment]
I just removed mine and i can now build, nopw just to get the transition link bug fixed and im fully back, maybe reverting gatsby version may help me...

**Comment by i-bsd** [comment]
@joebentaylor1995 Yes but disabled earlier today.

**Comment by i-bsd** [comment]
@joebentaylor1995 I had a weird issue today where I couldn't run `gatsby develop` (it would just show a blank white screen with no error messages or console output). Disabled preact and it worked.

But I still can't use the latest version of React with the jsx-transform thing. Had to downgrade to previous version.

**Comment by joebentaylor1995** [comment]
Yeah uive disabled it from my gatsby config and i can now build. this is a crazy issue

**Comment by i-bsd** [comment]
@joebentaylor1995 Just to clarify - are you using latest version React@16.14.0 with preact disabled, and everything works?

**Comment by gaearon** [comment]
>I think it's an issue with React (jsx-transform): facebook/react#20036

What makes you think there's an issue in React? The issue you're linking to has no reproducing case so it's likely a configuration problem in the reporter's setup. We didn't close it out of courtesy for now, but there's nothing there that indicates a React problem.

**Comment by ttstauss** [comment]
@joebentaylor1995, yes I have Preact installed. I updated gatsby-plugin-preact to 4.0.16 from 4.0.15 and React back to 16.14.0 from 16.13.1. I also upgraded gatsby from 2.24.78 to 2.24.80. So far I've been able to build successfully with these changes.

**Comment by gaearon** [comment]
It seems like the common thread is that you use React in development and Preact in production. To me, this sounds like an extremely fragile setup because Preact is known to have behavior differences and incompatibilities with React, but that's your call. What I think is happening here is that Gatsby detects React supports the new JSX transform (so it uses it), but it isn't aware of the Preact override, and I think maybe Preact doesn't support it yet (?)

**Comment by adonig** [comment]
One hour ago there was [an update to Preact](https://github.com/preactjs/preact/releases/tag/10.5.5) but sadly the problem still persists. I'm not sure whether the problem is caused by preact or by [gatsby-plugin-preact](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-preact). For now the best workaround is to pin react to "<16.14.0" until the issue gets resolved.

**Comment by wardpeet** [comment]
I've installed `gatsby@2.24.77` with `preact@10.5.5` and `gatsby-plugin-preact@4.0.16` and I don't get an issue. We published a fix where we rollbacked the automatic jsx part

**Comment by tujoworker** [comment]
In my case, it is the MDX plugin that does not find the jsx runtime:
`Can't resolve 'react/jsx-runtime' in '.../node_modules/gatsby-plugin-mdx'`

Any idea @wardpeet on that?

**Comment by wardpeet** [comment]
@tujoworker have you updated all packages?

**Comment by w3bdesign** [comment]
React 17 is currently not yet fully supported with Gatsby as the ecosystem hasn't updated yet.
 
This has been mentioned in other issues here.

I would stay with version 16 until the ecosystem has matured a little bit more, which will probably happen in a week or more.

**Comment by ascorbic** [comment]
I'm going to close this, as it should be fixed now. If anyone can reproduce it with the latest version of gatsby, please can you share a minimal reproduction and reopen.

**Comment by sidyes** [comment]
> @joebentaylor1995 I had a weird issue today where I couldn't run `gatsby develop` (it would just show a blank white screen with no error messages or console output). Disabled preact and it worked.
> 
> But I still can't use the latest version of React with the jsx-transform thing. Had to downgrade to previous version.

I am facing the same issue. Do you have a fix for that by now?

**Comment by i-bsd** [comment]
> > @joebentaylor1995 I had a weird issue today where I couldn't run `gatsby develop` (it would just show a blank white screen with no error messages or console output). Disabled preact and it worked.
> > But I still can't use the latest version of React with the jsx-transform thing. Had to downgrade to previous version.
> 
> I am facing the same issue. Do you have a fix for that by now?

This issue hasn't been fixed yet.

I have comment out `gatsby-plugin-preact` when I'm developing, and then uncomment it before I push for deployment.

Latest version of React also still doesn't work.

Not sure what the status on all this is.

**Comment by w3bdesign** [comment]
> 
> 
> > > @joebentaylor1995 I had a weird issue today where I couldn't run `gatsby develop` (it would just show a blank white screen with no error messages or console output). Disabled preact and it worked.
> > > But I still can't use the latest version of React with the jsx-transform thing. Had to downgrade to previous version.
> > 
> > 
> > I am facing the same issue. Do you have a fix for that by now?
> 
> This issue hasn't been fixed yet.
> 
> I have to comment out `gatsby-plugin-preact` when I'm developing, and then uncomment it before I push for deployment.
> 
> Latest version of React also still doesn't work.
> 
> Not sure what the status on all this is.

Can you share a minimal reproduction?

**Comment by Bilal-Bangash** [comment]
@i-bsd @w3bdesign 
**Description**
I can no longer run gatsby develop with react-bootstrap and preact 
![image](https://user-images.githubusercontent.com/53056567/151654239-549b5a36-bd9a-4e64-b63f-3c0ec3881f7f.png)
![image](https://user-images.githubusercontent.com/53056567/151654306-3ae81a4f-ca21-4c25-b720-2c31cad3d1e2.png)

**Comment by w3bdesign** [comment]
@Bilal-Bangash 

Try this:

Rm -rf node_modules
Rm package-lock.json
Npm i

**Comment by Bilal-Bangash** [comment]
> @Bilal-Bangash
> 
> Try this:
> 
> Rm -rf node_modules Rm package-lock.json Npm i

Yes I did that but still the same result

**Comment by w3bdesign** [comment]
@Bilal-Bangash 

Try this:

https://exerror.com/module-not-found-error-cant-resolve-react-jsx-runtime/
