### ISSUE TITLE
gatsby-plugin-preact@5 HMR not working

### ISSUE THREAD

**Issue by pieh** [gatsbyjs/gatsby#30190]
Split from https://github.com/gatsbyjs/gatsby/issues/30183

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clone https://github.com/pieh/gatsby-plugin-preact-hmr-repro install deps, start `gatsby develop` try to edit js files

### Expected result

Changes are not hot reloaded, HMR is not connected

### Actual result

Changes to hot reload without having to do manual refresh

Some details:
seems like removal of `webpack-hot-middleware/client` in https://github.com/gatsbyjs/gatsby/pull/29540/files#diff-2e138e460e250687879a19f1bfe02bec6b9d8b1e07bf2093c8df9b2cc9ae47ed doesn't play well with `prefresh` hot reloading - this as opposed to `react-refresh` seem to need HMR client connection setup separately

**Comment by cortopy** [comment]
This is also happening with me. Just removing the plugin brings HMR back

**Comment by alanontheweb** [comment]
Same here

**Comment by wildpow** [comment]
Same, Any word on this subject?

**Comment by wildpow** [comment]
I've been using this work around tell this issue gets sorted. I'm sure I'll get bit by some package not likeing Preact in production but I'm getting HMR and bundle/speed savings in production.

```javascript
//  gatsby.config.js

const cfg = {
  plugins: ['gatsby-plugin-stuff']
}

if (process.env.NODE_ENV === 'production') {
  const preact = 'gatsby-plugin-preact'
  cfg.plugins.push(preact)
}

module.exports = cfg
```

**Comment by davwheat** [comment]
Another way to work around this issue is below. This is my favourite way as it lets you very easily add more prod-only plugins, like analytics.

```js
//  gatsby.config.js

const prodPlugins = process.env.NODE_ENV === 'production' ? [`gatsby-plugin-preact`] : []

module.exports = {
  // config...
  plugins: [
    // Plugins to use all of the time
    ...prodPlugins,
  ],
}
```

**Comment by brvnonascimento** [comment]
However it can cause unexpected bugs in production, right?

**Comment by kelvindecosta** [comment]
Hey @pieh 

I think this is fixed with #29831.
HMR works with `preact` now.

Thanks again for opening this issue!

**Comment by wildpow** [comment]
I will give it a shot today and repot back

**Comment by brvnonascimento** [comment]
I'm still experiencing this issue, unfortunately. Is there something I need to do to get the latest update?

`yarn why` results:
=> Found "gatsby@3.11.0"
=> Found "preact@10.5.14"
=> Found "preact-render-to-string@5.1.19"
=> Found "gatsby-plugin-preact@5.11.0"

**Comment by albv** [comment]
I am also having this issue with `gatsby@4.1.0` and `gatsby-plugin-preact@6.1.0`

**Comment by cortopy** [comment]
@kelvindecosta would you mind reopening? Like other users, I'm also still experiencing this issue on `gatsby-plugin-preact@6.5.0` and `gatsby@4.5.4`
