### ISSUE TITLE
DeprecationWarning: deprecated folder mapping "./" in exports field due to outdated PostCSS dependency on Node v16+

### ISSUE THREAD

**Issue by richiksc** [gatsbyjs/gatsby#31108]
## Description

```
(node:69091) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./"  in the "exports" field module resolution of the package at [PROJECT_DIR]/node_modules/postcss/package.json.
```

On `gatsby build` or `gatsby develop` with Node v16+. This is on macOS 11.2, ARM64. Here is the related postcss issue (https://github.com/postcss/postcss/issues/1561), which was fixed in 8.2.11. This is largely due to Gatsby relying on an old version of `css-minimizer-webpack-plugin`, which still uses postcss v7. This is easily visible through `npm ls postcss`.

### Steps to reproduce

Create a new Gatsby site on Node 16+. Run `npx gatsby build` or `npm run build`.

### Expected result

No deprecation warning.

### Actual result

Deprecation warning.

### Environment

```

  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /opt/homebrew/bin/node
    npm: 7.10.0 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-offline: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
```

**Comment by tu4mo** [comment]
I'm still getting this with Gatsby v3.8.

**Comment by abouthalf** [comment]
This still occurs with Gatsby 3.9 and Node v16.x

**Comment by tu4mo** [comment]
Looks like it's fixed in https://github.com/gatsbyjs/gatsby/pull/32208, so probably in v3.10 release.

**Comment by panzacoder** [comment]
I'm still seeing this issue on Gatsby v4.3.0. node --trace-deprecations provides the following:

```(node:78588) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/jshebert/Development/lightstep-web/node_modules/postcss-js/package.json.
Update this package.json to use a subpath pattern like "./*".
    at emitFolderMapDeprecation (node:internal/modules/esm/resolve:99:11)
    at packageExportsResolve (node:internal/modules/esm/resolve:688:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at map (/Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:45:41)
    at Array.map (<anonymous>)
    at getTreeFromNodeModules (/Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:40:49)
    at /Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:53:11
    at async Promise.all (index 3)
    at getTreeFromNodeModules (/Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:39:3)
    at /Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:53:11
    at async Promise.all (index 41)
    at getTreeFromNodeModules (/Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/utils/gatsby-dependents.ts:39:3)
    at parseQueries (/Users/jshebert/Development/lightstep-web/node_modules/gatsby/src/query/query-compiler.js:119:32)

**Comment by panzacoder** [comment]
I'm still seeing this issue on Gatsby v4.3.0. `NODE_OPTIONS=--trace-deprecations yarn develop` provides the following:

```(node:78588) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at <project_root>/node_modules/postcss-js/package.json.
Update this package.json to use a subpath pattern like "./*".
    at emitFolderMapDeprecation (node:internal/modules/esm/resolve:99:11)
    at packageExportsResolve (node:internal/modules/esm/resolve:688:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at map (<project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:45:41)
    at Array.map (<anonymous>)
    at getTreeFromNodeModules (<project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:40:49)
    at <project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:53:11
    at async Promise.all (index 3)
    at getTreeFromNodeModules (<project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:39:3)
    at <project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:53:11
    at async Promise.all (index 41)
    at getTreeFromNodeModules (<project_root>/node_modules/gatsby/src/utils/gatsby-dependents.ts:39:3)
    at parseQueries (<project_root>/node_modules/gatsby/src/query/query-compiler.js:119:32)
