### ISSUE TITLE
gatsby-source-graphql error on gatsby build (and vercel deployment) for wordpress sourced site

### ISSUE THREAD

**Issue by cordial** [gatsbyjs/gatsby#31502]
## Description

In a site I've not touched in a year (but I'm on a different machine), gatsby build is failing with this error - 
"success delete html and css files from previous builds - 0.021s
success initialize cache - 0.010s
success copy gatsby files - 0.058s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.004s

 ERROR #11321  PLUGIN

"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

[object Object]

not finished source and transform nodes - 1.052s"

This also happens if i try and deploy on the production version of the site, which is deployed at Vercel. 

### Steps to reproduce

1. Create WP sourced site 
2. Build

Sorry I can't really reproduce this easily. 

### Expected result

Should build successfully as before. 

### Actual result

The build should work.

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nodenv/versions/14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nodenv/versions/14.15.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 82.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.18.12 => 2.18.12
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-emotion: ^4.1.18 => 4.1.18
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.5 => 2.3.5
    gatsby-plugin-sitemap: ^2.2.24 => 2.2.24
    gatsby-plugin-theme-ui: ^0.2.53 => 0.2.53
    gatsby-source-filesystem: ^2.1.40 => 2.1.40
    gatsby-source-graphql: ^2.1.29 => 2.14.0
    gatsby-transformer-sharp: ^2.3.7 => 2.3.7
  npmGlobalPackages:
    gatsby-cli: 3.5.0

**Comment by vladar** [comment]
Hi @cordial 

Sorry to hear you're running into an issue. Looks like you are on a very outdated version of both `gatsby` and `gatsby-source-graphql`. It is highly likely that the issue is already fixed. Can you upgrade to the latest version of both `gatsby` and `gatsby-source-graphql` and try it again?

If the issue stays there after you upgrade, ping me and I'll re-open it.

**Comment by cordial** [comment]
hey thanks for the prompt reply - ive upgraded both and i get pretty much the same thing - 
"success open and validate gatsby-configs - 0.044s
warn Plugin gatsby-plugin-react-helmet is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-emotion is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-transformer-sharp is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.12.1
warn Plugin gatsby-plugin-sitemap is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-theme-ui is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.13.1
warn Plugin gatsby-plugin-manifest is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.4.0
warn Plugin gatsby-source-filesystem is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.2.0
warn Plugin gatsby-plugin-react-helmet is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-emotion is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-transformer-sharp is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.12.1
warn Plugin gatsby-plugin-sitemap is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-theme-ui is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.13.1
warn Plugin gatsby-plugin-manifest is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.4.0
warn Plugin gatsby-source-filesystem is not compatible with your gatsby version 3.5.0 - It requires gatsby@^2.2.0
success load plugins - 0.580s
success onPreInit - 0.029s
success initialize cache - 0.004s
success copy gatsby files - 0.066s
success onPreBootstrap - 0.012s
success createSchemaCustomization - 0.006s

 ERROR #11321  PLUGIN

"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:



not finished source and transform nodes - 0.511s" It's not even saying object object now

**Comment by cordial** [comment]
Thanks for the quick reply. I updated those versions (and the dependencies of that). It's still not working when i do a gatsby build/develop and I'm getting even less of an error message now though - 
"gatsby build
Using environment config: 'production'
This WordPress Endpoint is used: 'https://api.thekidsclubsfamily.com/graphql'
success open and validate gatsby-configs - 0.046s
success load plugins - 0.391s
success onPreInit - 0.039s
success initialize cache - 0.004s
success copy gatsby files - 0.066s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.008s

 ERROR #11321  PLUGIN

"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:



not finished source and transform nodes - 1.388s"

**Comment by cordial** [comment]
the build eventually built while not properly succeeding and trashed the live site. And Vercel won't rollback because the last successful build was not done in git and was on an old machine. Really glad i upgraded.
