### ISSUE TITLE
Error: We couldn't find the correct component chunk with the name [...]

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#33112]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

**TL;DR, Gatsby apps are prone to crash whenever any component file (including pages and templates) is renamed or removed.**

My Sentry reports get fairly frequent errors like this one:

```
Error: We couldn't find the correct component chunk with the name component---src-templates-city-city-jsx
  at loadComponent(webpack://@shopnishe/web-app/./.cache/loader.js:493:15)
  at ? (webpack://@shopnishe/web-app/./.cache/loader.js:247:42)
```

I finally accidentally reproduced it today by reviving a tab that had been asleep for 14 days, which immediately hung so hard that the Sentry error reporter didn't even pop up.

Thankfully the report did get through to Sentry, so I have a very good idea of what's going on here. It's very similar to #18866, probably requires a similar short-term workaround (refresh the page), and may also require a better long-term solution.

### Reproduction Link

https://www.shopnishe.com/ca/on/toronto/

Given the nature of the issue, it's not possible to build a minimal reproduction. Instead, build any starter (or any other project), then follow the steps to reproduce.

### Steps to Reproduce

1. Open a tab.
2. Let it fall asleep.
3. Rename a component file (the page component works well).
4. Rebuild the site.
5. Wake up the tab.

### Expected Result

The site works when resumed. If a component chunk fails to load due to an interim deployment, the page is reloaded.

### Actual Result

<details><summary>Sentry screenshot</summary>

![image](https://user-images.githubusercontent.com/1505561/132700074-9980ab26-a730-4292-b483-8fd2a258c298.png)

</details>

- The sleeping tab, once awakened, loads the latest `app-data.json`, then the latest `page-data.json` for the current route.
- `page-data.json` references a `componentChunkName` that did not exist in the sleeping tab's release.
- The component is not found in the Webpack cache, causing the loader to throw an error.
- The app crashes so hard, Sentry can't even show its crash reporter UI.

I think this `throw`:

https://github.com/gatsbyjs/gatsby/blob/f03fb94eeb6e10ff4ac83b37ab40f496654f6758/packages/gatsby/cache-dir/loader.js#L492-L496

Is too aggressive given how easily these conditions can be recreated.

I think it would be better to check here if `webpackCompilationHash` changed, and if so, refresh the top window instead of throwing.

The range of affected devices is quite wide; it may impact SEO, too, as 40% of impacted users were Googlebots.

### Environment

Gatsby Cloud hosting.

**Comment by aaronadamsCA** [comment]
Probably deserves a not-stale tag, since it guarantees real-world app crashes every time components are refactored.

**Comment by Leksat** [comment]
In our case this error appears in `gatsby develop` mode on a different condition. We have Gatsby connected with Drupal via `gatsby-graphql-toolkit`. What happens:
- `gatsby develop` started when there is no `SomeSpecialType` objects, so `some-special-type-page.tsx` template is not used
- Then we publish a special page in Drupal
- This triggers Gatsby's `/__refresh`
- `SomeSpecialType` object is created
- Accessing Gatsby's `/path-to-special-page` gives the error

This does not happen with `gatsby build` having caches on re-run.

It would be fine to just live with this. But it actually fail Gatsby Cloud builds. Gatsby Cloud reports a different error:
```
failed Building static HTML for pages - 0.477s
  211 |     const { componentChunkName, staticQueryHashes = [] } = pageData
      |                                 ^
  213 |
  214 |     const staticQueryUrls = staticQueryHashes.map(getStaticQueryUrl)
  215 |
> 212 |     const pageComponent = await asyncRequires.components[componentChunkName]()
  WebpackError: TypeError: asyncRequires.components[componentChunkName] is not a   function
  - static-entry.js:212 
    @nagra/website/.cache/static-entry.js:212:33
  - interopRequireWildcard.js:25 
    node_modules/@babel/runtime/helpers/interopRequireWildcard.js:25:1
```
But I guess it's caused by the same reason: missing template data in Gatsby's cache.

**Comment by aaronadamsCA** [comment]
I believe #34225 would have resolved this, but I'd prefer to wait and see if anyone else can confirm, since our traffic is too low post-holiday to trust that an empty log means that it's fixed!

**Comment by jaska120** [comment]
We have seen similar errors in Sentry, so I guess https://github.com/gatsbyjs/gatsby/pull/34225 did not resolve the issue.

**Comment by LekoArts** [comment]
Hi!

I'm closing this as a stale issue as in the meantime Gatsby 4 and related packages were released. You can check our [Framework Version Support Page](https://www.gatsbyjs.com/docs/reference/release-notes/gatsby-version-support/) to see which versions currently receive active support. If this is a feature request, please [create a discussion](https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests) as we moved feature requests from issues to GitHub Discussions.

Please try the mentioned issue on the latest version (using the `next` tag) and if you still see this problem, open a new bug report. It **must** include a [minimal reproduction](https://gatsby.dev/reproduction).

Thanks!

**Comment by brunopinna** [comment]
This is still an issue in Gatsby 5.5

**Comment by victor-checkr** [comment]
Hello my team is currently working on a project and I recently upgraded to Gatsby V5.11, and enabled Partial Hydration in `gatsby-config.js`. Once I deployed our site to Netlify I started running into the  `Error: We couldn't find the correct component chunk with the name` issue. 

This error would not resolve regardless of `gatsby clean` browser cache flush or even modifying my build command to include gatsby clean `"build": "npm run clean && gatsby build"`.

I did some debugging and was able to figure out the Partial Hydration flag being True was the cause of the error. I disabled Partial Hydration redeployed my application on Netlify and the error is gone.

**Comment by ShamarYarde** [comment]
If you are experiencing this problem on Safari browser, you can try the following command whilst on the tab where your website or web application is open: `Option + Command + E`.

References: 

StackOverflow. Gatsby error when creating a new route: Preparing requested page. https://stackoverflow.com/a/74145453/8121551. (Accessed 23 September, 2024).

**Comment by Jeremuelle** [comment]
Still reproducible on Gatsby 5.11.0. In my case, I had to use the Gatsby Head API, replacing react-helmet, which was causing issues with SEO. I had to convert the pages from .js to .jsx, which was described in this issue. Any updates for people who had this issue and fixed?
