### ISSUE TITLE
WebpackError: TypeError: merge is not a function (from plugin: gatsby-plugin-react-helmet)

### ISSUE THREAD

**Issue by krismorf** [gatsbyjs/gatsby#33274]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When updating to the latest Gatsby releases (3.14.0 or next) builds are failing with the following error:

```
Building static HTML failed for path "/tags/cryptocurrency/" 👈 this is random

See our docs page for more info on this error: https://gatsby.dev/debug-html


  100 |   }
  101 |
> 102 |   return merge(a, b, { arrayMerge: combineMerge })
      |          ^
  103 | }
  104 |
  105 | export default async function staticPage({


  WebpackError: TypeError: merge is not a function (from plugin: gatsby-plugin-react-helmet)
```

### Reproduction Link

. 

### Steps to Reproduce

```
 babel-preset-gatsby              1.13.0  →  1.14.0     
 gatsby                           3.13.1  →  3.14.0     
 gatsby-plugin-feed               3.13.0  →  3.14.0     
 gatsby-plugin-gatsby-cloud        3.1.0  →   3.2.0     
 gatsby-plugin-google-tagmanager  3.13.0  →  3.14.0     
 gatsby-plugin-image              1.13.0  →  1.14.0     
 gatsby-plugin-manifest           3.13.0  →  3.14.0     
 gatsby-plugin-react-helmet       4.13.0  →  4.14.0     
 gatsby-plugin-sharp              3.13.0  →  3.14.0     
 gatsby-plugin-sitemap             4.9.0  →  4.10.0     
 gatsby-source-filesystem         3.13.0  →  3.14.0     
 gatsby-source-wordpress          5.13.0  →  5.14.0     
 gatsby-transformer-sharp         3.13.0  →  3.14.0
```

### Expected Result

Should build

### Actual Result

Doesn't build

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  npmPackages:
    gatsby: 3.13.1 => 3.13.1
    gatsby-plugin-eslint: 4.0.0 => 4.0.0
    gatsby-plugin-feed: 3.13.0 => 3.13.0
    gatsby-plugin-gatsby-cloud: 3.1.0 => 3.1.0
    gatsby-plugin-google-tagmanager: 3.13.0 => 3.13.0
    gatsby-plugin-image: 1.13.0 => 1.13.0
    gatsby-plugin-manifest: 3.13.0 => 3.13.0
    gatsby-plugin-netlify: 3.14.0 => 3.14.0
    gatsby-plugin-react-helmet: 4.13.0 => 4.13.0
    gatsby-plugin-react-helmet-canonical-urls: 1.4.0 => 1.4.0
    gatsby-plugin-react-i18next: 1.1.1 => 1.1.1
    gatsby-plugin-sharp: 3.13.0 => 3.13.0
    gatsby-plugin-sitemap: 4.9.0 => 4.9.0
    gatsby-plugin-theme-ui: 0.11.2 => 0.11.2
    gatsby-source-filesystem: 3.13.0 => 3.13.0
    gatsby-source-google-spreadsheets: 3.0.8 => 3.0.8
    gatsby-source-wordpress: 5.13.0 => 5.13.0
    gatsby-source-youtube-v3: 3.0.2 => 3.0.2
    gatsby-transformer-sharp: 3.13.0 => 3.13.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by krismorf** [comment]
Hi and thanks for the reply! See here for the reproduction https://github.com/krismorf/gatsby-merge-error

It is a huge site and tried to remove as many things as possible, you can reach the error with `npm run build`.

I've sent you the `.env` file in discord.

Thanks!

**Comment by LekoArts** [comment]
Hi,

please provide a minimal reproduction as it's too much going on in the site you linked. A plugin you're using might be at fault and with this it's not clear where the error lies.

**Comment by ppatel31** [comment]
may be "deepmerge": "^4.2.2" cause issue which is used in gatsby. you could check it.

**Comment by ekon97** [comment]
Hi,

I have the same issue as well. 

**Reproduction Link**

https://github.com/ekon97/Gatsby-WebpackError-Merge

**Steps to Reproduce**

1. npm install
2. gatsby build

**Comment by ppatel31** [comment]
During the build, it also stuck at

success Building production JavaScript and CSS bundles - 142.311s
success Rewriting compilation hashes - 0.010s
success Writing page-data.json files to public directory - 0.904s - 1760/1760 1947.13/s
success Caching JavaScript and CSS webpack compilation - 24.061s

After some time, it will give error

WebpackError: TypeError: merge is not a function (from plugin: gatsby-plugin-react-helmet)

**Comment by LekoArts** [comment]
<details>
 <summary>Debugging Screenshots</summary>

> **Reproduction Link**
> [ekon97/Gatsby-WebpackError-Merge](https://github.com/ekon97/Gatsby-WebpackError-Merge)
> **Steps to Reproduce**
> 1. npm install
> 2. gatsby build

I've removed the package-lock.json file, removed the `flags` inside `gatsby-config.js`, did a `yarn` and run `gatsby build` and it works all fine:

![image](https://user-images.githubusercontent.com/16143594/134463892-7ef8fd24-e993-4d3e-bf3e-f051ea82759c.png)

When I use your exact setup with the lock file + flags I also get the error:

![image](https://user-images.githubusercontent.com/16143594/134464177-29cc9615-b330-4ded-98e1-1016e0788150.png)

When I then check the installed version of `deepmerge` I see:

```shell
Gatsby-WebpackError-Merge on  main is 📦 v1.0.0 via ⬢ v14.17.6
➜ npm ls deepmerge
bikifi@1.0.0 /home/lennart/development/playground/Gatsby-WebpackError-Merge
├─┬ @wordpress/block-library@6.0.0
│ └─┬ @wordpress/components@17.0.0
│   └─┬ react-dates@17.2.0
│     └─┬ react-with-styles@3.2.3
│       └─┬ react-with-direction@1.3.1
│         └── deepmerge@1.5.2
├─┬ gatsby@3.14.0
│ └── deepmerge@4.2.2
└─┬ gatsby-plugin-sharp@3.14.0
  └─┬ probe-image-size@6.0.0
    └── deepmerge@4.2.2
```

In `node_modules` you can see that `1.5.2` is installed, not `4.2.2`:

![image](https://user-images.githubusercontent.com/16143594/134464712-94173c91-beb0-4230-9d0d-78b06ed11065.png)

</details>

---

Your usage of `@wordpress/block-library@6.0.0` and its usage of this old `deepmerge` package is at fault. I've tried deleting `package-lock.json` and doing a fresh install but it still fails. As often, `yarn` seems to be smarter here as it dedupes to the latest version:

```shell
Gatsby-WebpackError-Merge on  main [✘?] is 📦 v1.0.0 via ⬢ v14.17.6 took 1m 5s
➜ yarn why deepmerge
yarn why v1.22.5
[1/4] Why do we have the module "deepmerge"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "deepmerge@4.2.2"
info Has been hoisted to "deepmerge"
info Reasons this module exists
   - Hoisted from "gatsby#deepmerge"
   - Hoisted from "gatsby-plugin-sharp#probe-image-size#deepmerge"
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "56KB"
info Disk size with transitive dependencies: "56KB"
info Number of shared dependencies: 0
=> Found "react-with-direction#deepmerge@1.5.2"
info This module exists because "@wordpress#block-library#@wordpress#components#react-dates#react-with-styles#react-with-direction" depends on it.
info Disk size without dependencies: "44KB"
info Disk size with unique dependencies: "44KB"
info Disk size with transitive dependencies: "44KB"
info Number of shared dependencies: 0
Done in 0.60s.
```

In https://github.com/gatsbyjs/gatsby/pull/33051 we've added `deepmerge` to our dependencies and you now might see this if a third-party library is using an outdated version. You can open an issue on the repository of that third-party library, send in a PR or use `yarn resolutions` to force the correct version.

Sadly there's not much more that we can do, that's just npm and its ecosystem 🤷

**Comment by Pearce-Ropion** [comment]
Oh boy, anyone using Formik is in for a surprise.

**Comment by llamerr** [comment]
Same problem. Switched from `npm` to `yarn` and now it's working

**Comment by lukemcdonald** [comment]
> Same problem. Switched from `npm` to `yarn` and now it's working

Likewise

**Comment by Pearce-Ropion** [comment]
Unfortunately switching from npm to yarn is not an option for me.

I submitted a PR https://github.com/formium/formik/pull/3353 to bump formik's version of deepmerge. 

I reverted to gatsby 3.13.1 for the meantime.

**Comment by ppatel31** [comment]
This issue is in Gatsby new version, i switch back to 3.11.1 & it is resolved.

**Comment by yashvekaria** [comment]
> Another temporary solution is adding explicitly `deepmerge` dependency to your project.

add deepmerge dependency and it worked

Thanks @pdeszynski

**Comment by doublejosh** [comment]
I just upgraded to Gatsby 4, this is still broken. Not sure why it's closed? @LekoArts

**Comment by Nikhil-Ladha** [comment]
I am too facing the same issue in Gatsby@latest.

**Comment by waleedshkt** [comment]
Looks like the issue is resolved in the latest gatsby release. I'm using gatsby v4.24.4

In my case, the build succeeds in the local server. But when building the gatsby site in docker container, this error still pops up. Seems like explicitly adding `deepmerge` dependency is the fix for now.

**Comment by aprilmintacpineda** [comment]
I got this error in Gatsby 5.8.1:

```
 ERROR  UNKNOWN

Truncated page data information for the failed page "/404/": {
  "errors": {},
  "path": "/404/",
  "slicesMap": {},
  "pageContext": {}
}

failed Building static HTML for pages - 4.251s

 ERROR #95313  HTML.COMPILATION

Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  88 |   }
  89 |
> 90 |   return merge(a, b, { arrayMerge: combineMerge })
     |          ^
  91 | }
  92 |
  93 | /**


  WebpackError: TypeError: merge is not a function
```

Adding deepmerge to my dependency (which is currently 4.3.1) solved it. I think gatsby should update to deepmerge 4.3.1

**Comment by unilimpio** [comment]
i ran into the issue after executing npm update.
I am not sure which module is creating the conflict.
But same as others, _npm install deepmerge_ eliminated the bug at least for now.
