### ISSUE TITLE
Dev Overlay error on Safari, Firefox (non v8 browsers)

### ISSUE THREAD

**Issue by Nosferatu31** [gatsbyjs/gatsby#36362]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Firefox presents a blank screen when trying to render the overlay showing errors in the development stage.

![imagem](https://user-images.githubusercontent.com/9095366/183989272-4598214f-a034-4906-abc8-c92f3e54ef47.png)

<hr>

However, Chrome is able to present it correctly

![imagem](https://user-images.githubusercontent.com/9095366/183989515-c4201667-633a-4af1-add7-e7cdbe45568d.png)

### Reproduction Link

https://github.com/Nosferatu31/gatsby-bug-repro

### Steps to Reproduce

1. `npm i`
2. `gatsby develop`
3. Accessing the site with Firefox and Chrome

### Expected Result

- Firefox:
    - Shows page with modal displaying information about the error

- Chrome:
  - Shows page with modal displaying information about the error

### Actual Result

- Firefox:
  - Console shows `Warning: Cannot update a component (DevOverlay) while rendering a different component (WrappedAccordionItem)...` error
  - Console shows `The above error occurred in the <WrappedAccordionItem> component: WrappedAccordionItem@webpack-internal:///./.cache/fast-refresh-overlay/components/runtime-errors.js:35:15...` error

- Chrome:
  - Shows page with modal displaying information about the error

### Environment

```shell
System:
    OS: Windows 10 10.0.19043 Build 19043
    CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
  Binaries:
    Node: 16.16.0 - c:\Program Files\nodejs\node.exe
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.ps1
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Firefox: 103.0.1 (64-bit)
    Chrome: 103.0.5060.134 (64-bit)
  npmPackages:
    gatsby: 4.20.0
    gatsby-plugin-emotion: 7.20.0
    gatsby-plugin-google-tagmanager: 4.20.0
    gatsby-plugin-image: 2.20.0
    gatsby-plugin-manifest: 4.20.0
    gatsby-plugin-mixpanel: 3.7.0
    gatsby-plugin-netlify: 5.0.1
    gatsby-plugin-offline: 5.20.0
    gatsby-plugin-purgecss: 6.1.2
    gatsby-plugin-react-helmet: 5.20.0
    gatsby-plugin-remove-trailing-slashes: 4.19.0
    gatsby-plugin-sharp: 4.20.0
    gatsby-plugin-sitemap: 5.20.0
    gatsby-source-cosmicjs: 1.2.1
    gatsby-source-filesystem: 4.20.0
    gatsby-transformer-sharp: 4.20.0
  npmGlobalPackages:
    gatsby-cli: 4.20.0
```

### Config Flags

DEV_SSR: false

**Comment by tyhopp** [comment]
Hi @Nosferatu31, we published this in `gatsby@4.22.0-next.1`. Feel free to install this version if you're interested to try it out now, otherwise it will land in the next stable release.

**Comment by marianhlavac** [comment]
This issue is still present in gatsby `v5.5.0`.

Reproducible by:

* Creating new Gatsby project via `npm init gatsby`
* Altering _index.tsx_ file (or any other) so it contains an **runtime error** (errors at build time are not affected)
* Open site in Safari and Chrome – Safari (16.2) shows blank page, while Chrome (109.0.5414.87) does not and displays the issue correctly.

![Screenshot 2023-02-06 at 12 17 40](https://user-images.githubusercontent.com/3010503/216958290-e8a4f1ec-a9b6-4b69-8e5a-d9e5e8cad41c.png)

I'd like to ask for reopening this issue, as it seems not solved. Alternatively I can create a new issue, but it seems related.

**Comment by faruqiatnodapo** [comment]
> This issue is still present in gatsby `v5.5.0`.
> 
> Reproducible by:
> 
> * Creating new Gatsby project via `npm init gatsby`
> * Altering _index.tsx_ file (or any other) so it contains an **runtime error** (errors at build time are not affected)
> * Open site in Safari and Chrome – Safari (16.2) shows blank page, while Chrome (109.0.5414.87) does not and displays the issue correctly.
> 
> ![Screenshot 2023-02-06 at 12 17 40](https://user-images.githubusercontent.com/3010503/216958290-e8a4f1ec-a9b6-4b69-8e5a-d9e5e8cad41c.png)
> 
> ```
> [Error] Warning: Cannot update a component (`DevOverlay`) while rendering a different component (`WrappedAccordionItem`).
> ```
> 
> Console contents
> I'd like to ask for reopening this issue, as it seems not solved. Alternatively I can create a new issue, but it seems related.

Yes, it happens with me to.

**Comment by Stesm** [comment]
Issue present in Gatsby 5.10.0 on safari 16.5 (18615.2.9.11.4)
![Снимок экрана 2023-08-04 в 14 25 32](https://github.com/gatsbyjs/gatsby/assets/1927198/5250d3da-b517-49ea-b553-667d6a9bb591)

**Comment by pauls-akmentins** [comment]
Experiencing the same on gastby@4.7.2 and latest Safari.

Any tips how can I atleast omit these errors and proceed with showing the contents of page except showing blank page in development mode?

**Comment by marijoo** [comment]
Same here – Safari Version 17.4.1 (19618.1.15.11.14) and gatsby@5.13.3
