### ISSUE TITLE
[gatsby-source-wordpress] TypeError: Cannot destructure property 'fields' of 'nodesType' as it is undefined

### ISSUE THREAD

**Issue by kyle-tully** [gatsbyjs/gatsby#37114]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Trying to setup Gatsby with Wordpress.  

"Encountered a critical error when running the buildNodeQueries build step."

"TypeError: Cannot destructure property 'fields' of 'nodesType' as it is undefined.
    at generateNodeQueriesFromIngestibleFields"

### Reproduction Link

na

### Steps to Reproduce

Fresh WP install with latest plugin versions of

- WP Gatsby
- WP GraphQL

graphql url is reachable and graphiql ide returns correct post data for a basic query.

Fresh Gatsby install with Wordpress.

- gatsby-source-wordpress url is set in gatsby-config.js

Run gatsby develop and get the above error.

### Expected Result

success

### Actual Result

error

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nodenv/shims/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nodenv/shims/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.62
    Firefox: 103.0.2
    Safari: 16.1
  npmPackages:
    gatsby: ^5.2.0 => 5.2.0 
    gatsby-plugin-image: ^3.2.0 => 3.2.0 
    gatsby-plugin-manifest: ^5.2.0 => 5.2.0 
    gatsby-plugin-sharp: ^5.2.0 => 5.2.0 
    gatsby-plugin-sitemap: ^6.2.0 => 6.2.0 
    gatsby-source-filesystem: ^5.2.0 => 5.2.0 
    gatsby-source-wordpress: ^7.2.0 => 7.2.0 
    gatsby-transformer-sharp: ^5.2.0 => 5.2.0 
  npmGlobalPackages:
    gatsby-cli: 5.2.0
```

**Comment by LekoArts** [comment]
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tsamantanis** [comment]
Experiencing the same. Cannot reproduce on a fresh install

**Comment by metanite** [comment]
also happens in v6.24.1

**Comment by tsamantanis** [comment]
Seems like it can be an issue caused by the latest update of the WPGRAPHQL plugin

**Comment by REDSoftwareRasmus** [comment]
Also experienced this issue this morning. 

+1 up on your suggestion @tsamantanis 
_"Seems like it can be an issue caused by the latest update of the WPGRAPHQL plugin"_

For a temporary fix before this is resolved I downloaded an older version of the WPGraphQL plugin `v12.3` [here](https://wordpress.org/plugins/wp-graphql/advanced/) and replaced the existing `v13.0`  on our Wordpress instance. Seems to havre resolved the issue. 

So the new WPGraphQL version seems to be the cultprit here.

**Comment by turbz** [comment]
@REDSoftwareRasmus  I actually downgraded to v12.3 and the issue was resolved.

**Comment by REDSoftwareRasmus** [comment]
Yeah that's what I did as well 😄 @turbz

**Comment by tsamantanis** [comment]
Downgrading WPGraphQL does fix the issue @REDSoftwareRasmus. Thanks!

**Comment by LekoArts** [comment]
Please open an issue on the WPGraphQL GitHub then. Thanks!

**Comment by TylerBarnes** [comment]
Hey everyone, the errors here come from upgrading WPGraphQL but are due to how `gatsby-source-wordpress` works. There were some breaking changes in the latest version of WPGraphQL that aren't noticeable for most users but break the assumptions `gatsby-source-wordpress` makes about WPGraphQL's schema.

I'm currently working on a fix for it and I'll post an update here when I have a new version of `gatsby-source-wordpress` for you.

Thanks!

**Comment by kyle-tully** [comment]
> 

Thanks, this fixed the issue for me too.

Downgraded to Version 1.12.2 of WPGraphQL plugin fixed it.

**Comment by corbin-c** [comment]
Exact same issue here after WPGraphQL update to 1.13.x, downgrading fixed it. Using an outdated version of a plugin in a production environment isn't a suitable long-term solution though.

**Comment by TylerBarnes** [comment]
Yesterday I identified the problem, I'm just reading through the code right now and updating it with the fix, as the fix needs to be applied in multiple places. I'll have a PR up today

**Comment by TylerBarnes** [comment]
Hey folks, it's taking a little longer than expected but I want to drop an update here. I've fixed all of the issues that were failing builds and causing connections to break. I'm now working through integration test failures on older versions of WPGraphQL. Once I can be sure the changes I made wont break sites on earlier versions of WPGraphQL I'll be able to ship the fix

**Comment by TylerBarnes** [comment]
I have a fix which is forward/backwards compatible with WPGraphQL! I released it as a canary here `gatsby-source-wordpress@7.3.0-alpha-wpgql-13.36`. I'll also flag [the PR](https://github.com/gatsbyjs/gatsby/pull/37134) as a hotfix as well so it's released asap after being approved

**Comment by amcc** [comment]
I've installed the alpha above and get the error below during the develop process, I had to upgrade everything to Gatsby v5 in order to get this far :


```js

success  gatsby-source-wordpress  writing GraphQL queries to disk at ./WordPress/GraphQL/ - 0.162s
success  gatsby-source-wordpress  ingest WPGraphQL schema - 2.204s
success createSchemaCustomization - 4.800s
success  gatsby-source-wordpress  MenuItem - 1.161s - fetched 0
success  gatsby-source-wordpress  Comment - 1.202s - fetched 1
success  gatsby-source-wordpress  Category - 1.282s - fetched 1
success  gatsby-source-wordpress  fetch root fields - 1.370s
success  gatsby-source-wordpress  ContentType - 1.531s - fetched 5
success  gatsby-source-wordpress  Menu - 1.096s - fetched 0
success  gatsby-source-wordpress  Post - 1.145s - fetched 1
success  gatsby-source-wordpress  PostFormat - 1.217s - fetched 0
success  gatsby-source-wordpress  Page - 1.264s - fetched 5
success  gatsby-source-wordpress  Story - 1.401s - fetched 10
success  gatsby-source-wordpress  UserRole - 0.992s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.016s - fetched 4
success  gatsby-source-wordpress  Tag - 1.139s - fetched 0
success  gatsby-source-wordpress  StudentTag - 2.496s - fetched 15
success  gatsby-source-wordpress  Student - 13.632s - fetched 253
success  gatsby-source-wordpress  User - 4.376s - fetched 180
success  gatsby-source-wordpress  MediaItem - 75.480s - fetched 2455
success  gatsby-source-wordpress  creating nodes - 75.484s
success  gatsby-source-wordpress  fetching nodes - 96.467s - 2930 total
success Checking for changed pages - 0.001s
success source and transform nodes - 96.662s
success building schema - 0.521s

 ERROR #11321  API.NODE.EXECUTION

"gatsby-node.js" threw an error while running the createPages lifecycle:

Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.

   7 |   const { createPage } = actions;
   8 |
>  9 |   const result = await graphql(`
     |                        ^
  10 |     {
  11 |       allWpStudent {
  12 |         edges {

File: gatsby-node.js:9:24



  Error: Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
  Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
  Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
  Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
  Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
  
  - graphql-runner.ts:129 GraphQLRunner.validate
    [gmd2021]/[gatsby]/src/query/graphql-runner.ts:129:14
  
  - graphql-runner.ts:218 GraphQLRunner.query
    [gmd2021]/[gatsby]/src/query/graphql-runner.ts:218:49
  
  - create-graphql-runner.ts:57 apply
    [gmd2021]/[gatsby]/src/bootstrap/create-graphql-runner.ts:57:8
  
  - create-pages.ts:36 wrappedGraphQL
    [gmd2021]/[gatsby]/src/services/create-pages.ts:36:47
  
  - gatsby-node.js:9 createStudentPages
    /Users/alistairmcclymont/Sites/gmd/gmd2021/gatsby-node.js:9:24
  
  - gatsby-node.js:115 Object.exports.createPages
    /Users/alistairmcclymont/Sites/gmd/gmd2021/gatsby-node.js:115:9
  
  - api-runner-node.js:487 runAPI
    [gmd2021]/[gatsby]/src/utils/api-runner-node.js:487:22
  
  - api-runner-node.js:638 Promise.catch.decorateEvent.pluginName
    [gmd2021]/[gatsby]/src/utils/api-runner-node.js:638:13
  
  - debuggability.js:384 Promise._execute
    [gmd2021]/[bluebird]/js/release/debuggability.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [gmd2021]/[bluebird]/js/release/promise.js:518:18
  
  - promise.js:103 new Promise
    [gmd2021]/[bluebird]/js/release/promise.js:103:10
  
  - api-runner-node.js:636 
    [gmd2021]/[gatsby]/src/utils/api-runner-node.js:636:16
  
  - util.js:16 tryCatcher
    [gmd2021]/[bluebird]/js/release/util.js:16:23
  
  - reduce.js:166 Object.gotValue
    [gmd2021]/[bluebird]/js/release/reduce.js:166:18
  

failed createPages - 0.101s
success createPagesStatefully - 0.064s
info Total nodes: 7888, SitePage nodes: 13 (use --verbose for breakdown)
success Checking for changed pages - 0.000s
success write out redirect data - 0.001s
success Build manifest and related icons - 0.079s
success onPostBootstrap - 0.081s
info bootstrap finished - 107.133s
success onPreExtractQueries - 0.001s

 ERROR  UNKNOWN

Missing onError handler for invocation 'extracting-queries', error was 'Error: Interface field WpEdgeType.node expected but
WpEnqueuedScriptConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.'. Stacktrace was 'Error: Interface field
WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.

Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
    at assertValidSchema (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/graphql/type/validate.js:59:11)
    at validate (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/graphql/validation/validate.js:63:35)
    at extractOperations (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/gatsby/src/query/query-compiler.js:213:18)
    at processQueries (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/gatsby/src/query/query-compiler.js:169:45)
    at compile (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/gatsby/src/query/query-compiler.js:80:19)
    at updateStateAndRunQueries (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/gatsby/src/query/query-watcher.ts:236:40)
    at extractQueries (/Users/alistairmcclymont/Sites/gmd/gmd2021/node_modules/gatsby/src/services/extract-queries.ts:18:3)'

⠸ extract queries from components
[                            ]   0.068 s 0/2 0% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs

```

**Comment by TylerBarnes** [comment]
@amcc is there a repo or api endpoint I can use to reproduce it?

**Comment by amcc** [comment]
@TylerBarnes sent in the wp-graphql slack (hope that's ok, rather than here)

**Comment by TylerBarnes** [comment]
@amcc thanks for the repro!

Turns out I published the last canary incorrectly, or from the wrong commit. This new canary version fixes the issue `gatsby-source-wordpress@7.3.0-alpha-wpgql-thirteen.20`

**Comment by TylerBarnes** [comment]
This is published in:
```
Successfully published:
 - gatsby-source-wordpress@7.2.1
lerna success published 1 package
```
and
```
Successfully published:
 - gatsby-source-wordpress@6.24.2
lerna success published 1 package
```

**Comment by aaronjtonner** [comment]
Sorry but I'm not quite sure what I need to do on my end to fix this but I'm still getting the errors:

![image](https://user-images.githubusercontent.com/66490932/206047346-019dd37d-8fe4-4bf4-93aa-dfad6cbad10e.png)

**Comment by TylerBarnes** [comment]
@aaronjtonner if you upgrade to the latest version of `gatsby-source-wordpress` it should go away

**Comment by aaronjtonner** [comment]
Thanks Tyler. That got rid of those errors and caused a new one, haven't seen any fixes for this and no idea where it's coming from:
![image](https://user-images.githubusercontent.com/66490932/206050897-e2e45a3f-76ee-422c-af6b-340e7d8649c4.png)

**Comment by TylerBarnes** [comment]
I haven't seen that before either. I recommend opening a new issue :)

**Comment by amcc** [comment]
I saw that too. Only on gatsby cloud, not a local build. Still built though

**Comment by Haldaug** [comment]
I still get the same [error](https://github.com/gatsbyjs/gatsby/issues/37114#issuecomment-1338166676) as @amcc after upgrading to `gatsby-source-wordpress@7.2.1`. The error message is the same:

``` 
ERROR #11321  API.NODE.EXECUTION
"gatsby-node.js" threw an error while running the createPages lifecycle:
Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
```

Using the `gatsby-source-wordpress@7.3.0-alpha-wpgql-thirteen.20` version I get this error instead:

```
Error executing the GraphQL query inside gatsby-plugin-sitemap:
 Field "nodeType" is not defined by type "WpContentNodeFilterInput".
  GraphQLError: Field "nodeType" is not defined by type "WpContentNodeFilterInput".
```

**Comment by TylerBarnes** [comment]
@Haldaug the error from the canary was because I needed to remove the nodeType field to support the latest WPGraphQL version. You should be able to use the __typename field instead. That's odd that the canary doesn't have the other errors though while the newly published version does 🤔 I'll look into that and see if I can figure out what's going on

**Comment by TylerBarnes** [comment]
@Haldaug any way I can use your repo to reproduce the problem?

**Comment by Haldaug** [comment]
I've invited you to view my repo, @TylerBarnes.

**Comment by TylerBarnes** [comment]
Thanks @Haldaug !

**Comment by aaronjtonner** [comment]
> I still get the same [error](https://github.com/gatsbyjs/gatsby/issues/37114#issuecomment-1338166676) as @amcc after upgrading to `gatsby-source-wordpress@7.2.1`. The error message is the same:
> 
> ```
> ERROR #11321  API.NODE.EXECUTION
> "gatsby-node.js" threw an error while running the createPages lifecycle:
> Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
> Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
> Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
> Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
> Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
> ```

I'm getting this same error

**Comment by tsamantanis** [comment]
I am also getting this error now. I think this issue can be reopened as it is caused by the latest update.

> > I still get the same [error](https://github.com/gatsbyjs/gatsby/issues/37114#issuecomment-1338166676) as @amcc after upgrading to `gatsby-source-wordpress@7.2.1`. The error message is the same:
> > ```
> > ERROR #11321  API.NODE.EXECUTION
> > "gatsby-node.js" threw an error while running the createPages lifecycle:
> > Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
> > Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
> > Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
> > Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
> > Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
> > ```
> 
> I'm getting this same error

**Comment by DanicaTo** [comment]
Me too. 

> I am also getting this error now. I think this issue can be reopened as it is caused by the latest update.
> 
> > > I still get the same [error](https://github.com/gatsbyjs/gatsby/issues/37114#issuecomment-1338166676) as @amcc after upgrading to `gatsby-source-wordpress@7.2.1`. The error message is the same:
> > > ```
> > > ERROR #11321  API.NODE.EXECUTION
> > > "gatsby-node.js" threw an error while running the createPages lifecycle:
> > > Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
> > > Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
> > > Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
> > > Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
> > > Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
> > > ```
> > 
> > 
> > I'm getting this same error

**Comment by TylerBarnes** [comment]
I narrowed down the issue, turns out the problem is I split the fix into 2 PR's. The first PR was the actual fix and the second was supposed to just be updating the integration tests. [This one line](https://github.com/gatsbyjs/gatsby/pull/37146/files#diff-ef2a58bcc19cacff2fdf0f66b9c0737a23e1ae1dda1d4c960993aa1035bb5a46R93) should've been in the first PR but was in the second. I marked that second PR to be backported and have a hotfix release so once that's released it should be fixed.
Sorry for the mistake folks! For now the canary version is identical to what's about to be released.

**Comment by TylerBarnes** [comment]
Gatsby 5 version of source-wordpress with the full fix is published as `gatsby-source-wordpress@7.2.2`. I verified this fixes the issue on a site I reproduced the problem on, so should actually be good this time.
The v4 compatible version isn't published just yet but should be soon.

**Comment by TylerBarnes** [comment]
It seems the removal of the `nodeType` field in the latest version is problematic for some folks. I'll add it back in. The alternative is to use the `contentType` field but it seems enough folks are using `nodeType` that it can't be removed without needing to change a lot of site queries which is a big problem.

Apologies for the rocky time here everyone. We're getting close to this problem being over, but there's a little more to go.

**Comment by aaronjtonner** [comment]
Thanks Tyler :)

**Comment by TylerBarnes** [comment]
The Gatsby 4 version was just published as `gatsby-source-wordpress@6.25.1`. I tested this on a site I could reproduce the issues on and it's working great.

This new version doesn't include a nodeType field fix though, that's coming soon.

**Comment by TylerBarnes** [comment]
I released a canary that adds back the `nodeType` field here `gatsby-source-wordpress@7.3.0-alpha-wpgql-thirteen.26`

**Comment by aaronjtonner** [comment]
I'm getting a graphql query error that I've never seen until now, not sure if this has anything to do with the update? The previous error is no longer there:

![image](https://user-images.githubusercontent.com/66490932/206326159-33305ecc-a63a-4085-a28b-d6cb6d7eeb62.png)

**Comment by hamiltonbrooke** [comment]
Hi Tyler,

Just upgraded to version 7.2.2.
Builds are failing on Netlify.

Is this related?

9:11:01 AM: error UNHANDLED REJECTION Interface field WpEdgeType.node expected but WpEnqueuedScriptConnectionEdgeType does not provide it.
9:11:01 AM: Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdgeType does not provide it.
9:11:01 AM: Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEdgeType does not provide it.
9:11:01 AM: Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does not provide it.
9:11:01 AM: Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does not provide it.
9:11:01 AM: 
9:11:01 AM: 
9:11:01 AM:   Error: Interface field WpEdgeType.node expected but WpEnqueuedScriptConnection  EdgeType does not provide it.
9:11:01 AM:   Interface field WpEdgeType.node expected but WpEnqueuedStylesheetConnectionEdg  eType does not provide it.
9:11:01 AM:   Interface field WpEdgeType.node expected but WpActionMonitorActionConnectionEd  geType does not provide it.
9:11:01 AM:   Interface field WpEdgeType.node expected but WpPluginConnectionEdgeType does n  ot provide it.
9:11:01 AM:   Interface field WpEdgeType.node expected but WpThemeConnectionEdgeType does no  t provide it.
9:11:01 AM:   
9:11:01 AM:   - graphql-runner.ts:129 GraphQLRunner.validate
9:11:01 AM:     [repo]/[gatsby]/src/query/graphql-runner.ts:129:14
9:11:01 AM:   
9:11:01 AM:   - graphql-runner.ts:218 GraphQLRunner.query
9:11:01 AM:     [repo]/[gatsby]/src/query/graphql-runner.ts:218:49
9:11:01 AM:   
9:11:01 AM:   - create-graphql-runner.ts:57 
9:11:01 AM:     [repo]/[gatsby]/src/bootstrap/create-graphql-runner.ts:57:8
9:11:01 AM:   
9:11:01 AM:   - create-pages-from-collection-builder.js:45 createPagesFromCollectionBuilder
9:11:01 AM:     [repo]/[gatsby-plugin-page-creator]/create-pages-from-collection-builder.js:    45:13
9:11:01 AM: Creating deploy upload records
9:11:01 AM:   
9:11:01 AM:   - create-page-wrapper.js:43 createPage
9:11:01 AM:     [repo]/[gatsby-plugin-page-creator]/create-page-wrapper.js:43:76
9:11:01 AM:   
9:11:02 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:11:01 AM:   - gatsby-node.js:135 
9:11:01 AM:     [repo]/[gatsby-plugin-page-creator]/gatsby-node.js:135:41
9:11:01 AM:   
9:11:01 AM:   - Array.forEach
9:11:01 AM:   
9:11:01 AM:   - gatsby-node.js:134 Object.createPagesStatefully
9:11:01 AM:     [repo]/[gatsby-plugin-page-creator]/gatsby-node.js:134:11
9:11:01 AM:   
9:11:01 AM: 
9:11:01 AM: not finished createPagesStatefully - 0.188s
9:11:01 AM: ​
9:11:01 AM: ────────────────────────────────────────────────────────────────
9:11:01 AM:   "build.command" failed                                        
9:11:01 AM: ─────────────────────────────────────────────────────────

**Comment by TylerBarnes** [comment]
Two new versions with the nodeType field fix were published earlier today: `gatsby-source-wordpress@7.2.3` and `gatsby-source-wordpress@6.25.2`.

@hamiltonbrooke are you able to share your WPGrphQL /graphql endpoint with me so I can reproduce the issue? My email is tyler@gatsbyjs.com if you don't want to share it publicly

**Comment by aaronjtonner** [comment]
Hi Tyler, I was not previously getting this error until after the update:
![image](https://user-images.githubusercontent.com/66490932/206578903-f3e92a22-a6dc-48b4-8080-263b28b2b4ee.png)

**Comment by TylerBarnes** [comment]
@aaronjtonner are you able to send me your WPGraphQL api endpoint so I can reproduce the problem? Our integration tests do test using `wp-graphql-acf` but perhaps there's some case we're not testing, or our test site doesn't have the same setup as you

**Comment by aaronjtonner** [comment]
Sure, here's the endpoint: https://staging.innerspiritphoto.com/graphql

**Comment by TylerBarnes** [comment]
Thanks @aaronjtonner

**Comment by TylerBarnes** [comment]
@aaronjtonner that might be due to a change in how WPGraphQL 0.13.0+ works. The field is named `aCF_BooksPage`, not `ACF_BooksPage` (notice the first letter is lowercase).

In WPGraphQL:
```graphql
{
  pages {
    nodes {
      aCF_BooksPage {
        fieldGroupName
      }
    }
  }
}
```

in Gatsby:
```graphql
{
  allWpPage {
    nodes {
      aCF_BooksPage {
        fieldGroupName
      }
    }
  }
}
```

**Comment by aaronjtonner** [comment]
Thanks Tyler, that fixed those errors!

Still dealing with a few other errors that might be due to something else.

**Comment by TylerBarnes** [comment]
I believe the last remaining issue is the problem you mentioned @hamiltonbrooke but since I'm not able to reproduce it I'm not able to fix it. Is anyone else seeing those same errors on the latest versions?

**Comment by mehov** [comment]
Still getting this issue on a website hosted with Gatsby Cloud

Wordpress (self-hosted):

- Jetpack 11.6
- WP Gatsby 2.3.3
- WP Githuber MD 1.16.1
- WP GraphQL 1.13.7

**Comment by edsonJordan** [comment]
> v12.3
There is only version 12.2

**Comment by TylerBarnes** [comment]
I'm going to close this since I haven't heard any more reports recently. If anyone is still running into problems, please respond here with reproduction steps or open a new issue and I can help you out. Thanks everyone for your patience on this issue and for helping me reproduce bugs!

**Comment by TylerBarnes** [comment]
@salmanamemon thanks for sharing, which issue are you having? A description of it + reproduction steps will help a lot.
thanks!

**Comment by salmanamemon** [comment]
Hi @TylerBarnes, It is almost the same as Jason Bahl mentioned.

**Description**
Updated a few days ago to 1.13.7 and I wasn't able to start my Gatsby app, not even in develop mode.

Tried to disable all plugins and the error still remained. Rolled back to 1.12.2, and everything works fine again. After re-activating all other plugins everything works fine

**Steps to reproduce**
"gatsby develop"

Additional context
**Detailed error:**

TypeError: Cannot destructure property 'fields' of 'nodesType' as it is undefined.
at generateNodeQueriesFromIngestibleFields (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/generate-queries-from-ingestable-types.js:155:13)
at buildNodeQueries
(/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/build-queries-from-introspection/build-node-queries.js:25:25)
at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)
at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:43:9)
at ingestRemoteSchema (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/steps/ingest-remote-schema/index.js:49:5)
at runSteps (/xxx/gatsbyapp/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)
at runAPI (/xxx/gatsbyapp/node_modules/gatsby/src/utils/api-runner-node.js:487:16)

WPGraphQL Version
1.13.0

WordPress Version
6.1.1

PHP Version
8.1

Additional enviornment details
No response

Please confirm that you have searched existing issues in the repo.
 Yes
Please confirm that you have disabled ALL plugins except for WPGraphQL.
 Yes
 My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by TylerBarnes** [comment]
@salmanamemon did you upgrade to the latest version of `gatsby-source-wordpress`?

**Comment by salmanamemon** [comment]
No gatbsy-source-wordpress is the same 
 "node_modules/gatsby-source-wordpress": {
      "version": "6.24.0",

**Comment by TylerBarnes** [comment]
@salmanamemon upgrade to the latest 6.x.x version of source-wordpress and it should start working. (`yarn install gatsby-source-wordpress@^6.0.0` / `npm install gatsby-source-wordpress@^6.0.0`)

**Comment by byebyers** [comment]
I am having the same issue here when updating PHP to 8.1. Is that part of the problem? 

gatsby-source-wordpress version: 6.25.3
WPGraphQL version: 1.13.7
WordPress version: 6.1.1

None of the above solutions worked. Right now I have a working site working with PHP 7.4 and will stick with that for now.

**Comment by TylerBarnes** [comment]
@byebyers I haven't heard reports of that yet, that's odd. Are you saying when you're on the latest versions of those plugins it works until you switch to PHP 8.1?

**Comment by mikeriley131** [comment]
I'm running into the same issue.
PHP 8.0
WP GraphQL 1.13.8
gatsby-source-wordpress 6.14.0

**Comment by byebyers** [comment]
@TylerBarnes I still need to troubleshoot a few things but at first glance, that is what it looks like on my end. I will follow up on this thread once I have more info.

**Comment by aaronjtonner** [comment]
Hi @TylerBarnes, not sure if this is the correct place for this, but I'm running into problems in local development. Everything is set up properly and I'm using local flywheel. Would this have anything to do with version updates?
![image](https://user-images.githubusercontent.com/66490932/219521906-f4a754ab-ccec-4514-8bdd-251b92fa0bfe.png)

**Comment by Daw-St** [comment]
> Hi @TylerBarnes, not sure if this is the correct place for this, but I'm running into problems in local development. Everything is set up properly and I'm using local flywheel. Would this have anything to do with version updates? ![image](https://user-images.githubusercontent.com/66490932/219521906-f4a754ab-ccec-4514-8bdd-251b92fa0bfe.png)

Have you managed to solve the issue? Could you share versions of WP GraphQL, WP Gatsby and gatsby-source-wordpress? I'm struggling with the same issue.
cc @TylerBarnes
