### ISSUE TITLE
Wrap routes with sCU that that does shallow compare check + blocks renders on hash changes

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#487]
https://github.com/gatsbyjs/gatsby/issues/462#issuecomment-251765800

**Comment by f0rr0** [comment]
Wasn't this resolved with https://github.com/gatsbyjs/gatsby/pull/467?

**Comment by KyleAMathews** [comment]
No — that just fixed react-router-scroll from storing extra scroll positions. The extra renders are still happening cause react-router pushes out location changes to the active routes.

**Comment by f0rr0** [comment]
oh! hmm yes missed this since I was using `catch-links

**Comment by ralphstodomingo** [comment]
I'm encountering a problem with `smooth-anchorate`: that library is fine, the problem is that, on hash location changes, my page rerenders.
Any updates on this? If none, any hints on where I can tackle this in the codebase?

**Comment by m-allanson** [comment]
Could this be done with [`replaceRouterComponent`](https://www.gatsbyjs.org/docs/browser-apis/#replaceRouterComponent)?

**Comment by KyleAMathews** [comment]
@ralphstodomingo what version of Gatsby are you on?

**Comment by KyleAMathews** [comment]
Also, rendering on hash changes is normally what people would want I believe. If you don't want that, implement shouldComponentRender in your page component and return false when only the hash changes.

**Comment by KyleAMathews** [comment]
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!
