### ISSUE TITLE
Anchor links don't work in develop

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#6309]
I have an element with the id `hash` on [my page](https://github.com/fk/gatsby-v2-anchor-link/blob/6d886ed4025a14f3e8605a9ed26e6331d7887f61/src/pages/index.js#L22):

```
<h1 id="hash">Headline with #hash</h1>
```

When running `gatsby develop`, opening a new browser window and accessing `http://localhost:8000/#hash`, I expect the page to jump to the element with the corresponding id `hash`. It doesn't: 

![image](https://user-images.githubusercontent.com/21834/42325197-c442aec0-8065-11e8-8352-f7d78cf51a6e.png)

Only when I either
* open just `http://localhost:8000/` and then add `#hash` to the URL in the browser address bar and hit "Enter" or
* run `gatsby build` and then open `http://localhost:9000/#hash`,

the page jumps to the element as expected:

![image](https://user-images.githubusercontent.com/21834/42325380-6323f062-8066-11e8-8b60-a13722a4bea2.png)

Repo here: https://github.com/fk/gatsby-v2-anchor-link

**Comment by fk** [comment]
Tested in Google Chrome (latest, Version 67.0.3396.99, also in an incognito window), Firefox Quantum v59.0.1 and latest v61.0.

**Comment by fk** [comment]
develop: https://www.dropbox.com/s/a3d8w02863ie2j6/develop.mov?dl=0
build: https://www.dropbox.com/s/s0yrqh72v4cohig/build.mov?dl=0

**Comment by m-allanson** [comment]
Thanks for the repo and detailed writeup! I can confirm I'm seeing the same thing. I wonder if this is a v2 regression or something that's been around since v1?

**Comment by fk** [comment]
I think it's a regression—I implemented the sidebar stuff on v1 first and don't remember that tripping me up at all. I will have to check to be sure tho.

**Comment by fk** [comment]
Ignore what I said earlier, must have been dreaming—AFAICS same thing happens on v1: https://github.com/fk/gatsby-v2-anchor-link/tree/topics/v1

**Comment by ExiaSR** [comment]
Any update?

**Comment by pieh** [comment]
This PR solves this: https://github.com/gatsbyjs/gatsby/pull/6777

**Comment by fk** [comment]
🎉

**Comment by m-allanson** [comment]
This should be fixed in `gatsby@2.0.0-beta.65`.

**Comment by alexfornuto** [comment]
I'm running Gatsby `^2.13.18` and am still experiencing this issue in develop mode with [this project](https://github.com/pantheon-systems/documentation)

**Comment by Anahkiasen** [comment]
Still having this issue as well on latest version

**Comment by philipp-sapronov** [comment]
I have the same issue, v. of Gatsby is 2.9.4

**Comment by DRD161** [comment]
I'm having a similar issue using Gatsby version 2.8.23. I am using styled components to style the Link for a nav like so:
`const NavItem = styled(props => <Link {...props} />)`
  font-size: 1.4rem;
  color: #eeeeee;
  margin: 20px 15px 0 0;
  padding-right: 15px;
  text-decoration: none;
  border-right: 2px solid #eeeeee;
  line-height: 80%;
  &:nth-child(4) {
    border-right: none;
  }
``
but none of the links are clickable. When I inspect the elements in the console I see the href and I can access the pages by using /page-name. I never had this problem and now suddenly it just popped up.

**Comment by philipp-sapronov** [comment]
Hi Dylan,

Thanks for your letter, unfortunately I've already lost the context of this
problem, i think you've solved somehow this one.
If not, you can describe in more detail and send me.

You can try to write: const NavItem = styled(Link)` /* styles */ `

If you see <a href="your link">your link</a>  in inspector, but link is not
clickable, it means that something wrong with the page.

Try to write <a href="your link"/> instead of <NavItem to="your link"/> and
check



вт, 7 янв. 2020 г. в 07:19, Dylan Davenport <notifications@github.com>:

**Comment by DRD161** [comment]
In my case it was me being a fool and not realizing I had an element overlapping the navigation 😅I got it working now though! Thanks for the reply nonetheless l.
