### ISSUE TITLE
[v2] Warning in browser console during gatsby serve (after build)

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#7713]
## Summary

Chrome throws a warning in console during gatsby serve.

## Relevant information

The warning is  : `The resource http://localhost:9000/static/d/708/path---en-869-cd4-rxXbyoDAkJ1rXH07VFHKZjmdHQI.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.`

It doesn't cause any problems, just throws a warning. Any clue as to why it does?

### Environment (if relevant)

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.611.0
  npmPackages:
    gatsby: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-image: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-link: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-canonical-urls: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-google-analytics: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-google-tagmanager: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-i18n: 0.4.2 => 0.4.2
    gatsby-plugin-manifest: 2.0.2-rc.0 => 2.0.2-rc.0
    gatsby-plugin-offline: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-purify-css: 2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: 3.0.0-rc.0 => 3.0.0-rc.0
    gatsby-plugin-remove-trailing-slashes: ^1.0.9 => 1.0.9
    gatsby-plugin-robots-txt: 1.3.0 => 1.3.0
    gatsby-plugin-sharp: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-sitemap: 2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-source-contentful: 2.0.1-rc.0 => 2.0.1-rc.0
    gatsby-transformer-remark: 2.1.1-rc.0 => 2.1.1-rc.0
    gatsby-transformer-sharp: 2.1.1-rc.0 => 2.1.1-rc.0

**Comment by johncmunson** [comment]
I'm getting this same issue, both when using `gatsby serve` and after deploying to netlify

**Comment by shannonjensen** [comment]
I am getting the same issue, throwing 7 of the same warnings for various js bundles

**Comment by RJGrunau** [comment]
I am as well. @rtm619 did you find solution?

**Comment by coughlanio** [comment]
I'm getting the following locally & running in S3 and Netlify: 

```
The resource https://foo.bar/static/d/520/path---offline-plugin-app-shell-fallback-a-30-c5a-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by michaelwermeester** [comment]
I encounter the same issue with the offline plugin (gatsby-plugin-offline).

**Comment by cardiv** [comment]
The site of [Gatsby](https://www.gatsbyjs.org/) and my new [npm.cardiv.de](https://npm.cardiv.de/) are throwing the same warnings for me (Chrome), but both for a json file which seems to come from the offline plugin.

**Comment by pieh** [comment]
We should defenitely drop `preload` link for .json from offline shell.

If anyone would want to take a stab at this:
We would need `gatsby-ssr.js` file in https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline/src

In there we would want to implement [`onPreRenderHTML`](https://www.gatsbyjs.org/docs/ssr-apis/#onPreRenderHTML) API hook:
 - check if `pathname` is `/offline-plugin-app-shell-fallback/` (seems like `pathname` is not documented in our API reference :/)
 - get list of head components (`getHeadComponents`)
 - filter out "preload" component for .json (we might want to check if `as` attribute is "fetch" and maybe for sanity check `href` (if it contains/starts with `/static/d/` )
 - use `replaceHeadComponents` to update the list (with one that has the preload link for that .json` file removed)

**Comment by kalm42** [comment]
Replying. I'll take a stab at this.

**Comment by Razatastic** [comment]
At first, this only happened locally, but now it's also happening on Netlify. Any resolution for this yet?

**Comment by judah-firewood** [comment]
Same

**Comment by jeroenoomsNL** [comment]
Same here!

**Comment by hupe1980** [comment]
Same here!
@pieh I have implemented your proposal and created a PR #13935

**Comment by futhr** [comment]
The issue is still there using: 

`gatsby-plugin-offline` v2.2.4
`gatsby` v2.13.31

```
The resource https://mydomain.netlify.com/page-data/offline-plugin-app-shell-fallback/page-data.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by ytric** [comment]
I am getting the same issue. any update?

**Comment by OWMC** [comment]
I saw this in search console. It seems Json data is not being seen by Google because of this. Which has SEO implications.

**Comment by barrymichaeldoyle** [comment]
A few months later and I'm still experiencing the same issue. Any updates?

**Comment by Z11** [comment]
Yeah i'm still seeing this issue

**Comment by Thieffen** [comment]
Same. Just updated from gatsby v2 to v3

**Comment by amankataria216** [comment]
Any update how to fix this issue

**Comment by zmcx16** [comment]
same issue on firefox, gatsby-plugin-offline": "^3.0.32

**Comment by Artemdanilov5** [comment]
same issue
