### ISSUE TITLE
gatsby-plugin-sharp tracedSVG crashes build

### ISSUE THREAD

**Issue by tylermenezes** [gatsbyjs/gatsby#8301]
## Description

Using tracedSVG on a file ending in .jpeg causes gatsby-plugin-sharp to report the following vague error:

```
error UNHANDLED EXCEPTION


  TypeError: Cannot read property 'bitmap' of undefined
  
  - Potrace.js:1000 Potrace._processLoadedImage
    [www]/[potrace]/lib/Potrace.js:1000:35
  
  - Potrace.js:1046 Jimp.<anonymous>
    [www]/[potrace]/lib/Potrace.js:1046:14
  
  - index.js:85 Jimp.throwError
    [www]/[jimp]/index.js:85:44
  
  - index.js:201 ReadFileContext.callback
    [www]/[jimp]/index.js:201:44
```

Of note, Twitter always uses .jpeg for its image suffix, so any images saved from Twitter will crash tracedSVG.

### Steps to reproduce

1. Upload a .jpeg file to Contentful
2. Load the image in GraphQL using `tracedSVG`

### Expected result

- Image is traced into an SVG, **or**
- Gatsby tells me which error could not be traced

### Actual result

Vague error message.

### Environment

```

  [4mSystem:[0m
    OS: Linux 4.13 Ubuntu 17.10 (Artful Aardvark)
    CPU: x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Shell: 5.2 - /usr/bin/zsh
  [4mBinaries:[0m
    Node: 8.11.2 - /usr/bin/node
    npm: 6.4.1 - /usr/bin/npm
  [4mBrowsers:[0m
    Chrome: 67.0.3396.62
    Firefox: 61.0.1
  [4mnpmPackages:[0m
    gatsby: ^2.0.0-rc.28 => 2.0.0-rc.28 
    gatsby-image: ^2.0.0-rc.4 => 2.0.0-rc.4 
    gatsby-plugin-catch-links: ^2.0.2-rc.1 => 2.0.2-rc.1 
    gatsby-plugin-manifest: ^2.0.2-rc.1 => 2.0.2-rc.1 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-react-next: next => 2.0.1-13 
    gatsby-plugin-remove-trailing-slashes: ^1.0.9 => 1.0.9 
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-sitemap: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-source-contentful: ^2.0.1-rc.9 => 2.0.1-rc.9 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.1-rc.3 
    gatsby-transformer-yaml: ^2.1.1-rc.6 => 2.1.1-rc.6 
  [4mnpmGlobalPackages:[0m
    gatsby-cli: 2.4.1

```

**Comment by kakadiadarpan** [comment]
@tylermenezes can you provide a reproduction repo for this? That would make it much easier to diagnose this issue.

**Comment by JanneVincit** [comment]
I can confirm the same error message in our project. The difference is that I haven't been able to fully isolate the issue on my part yet. Though this issue is so far the only one, that might give me a hint on the issue.
The error on our project comes randomly, not on every build. I removed the tracedSVG fragment, from the code and so far it seems to work more reliably, but in my case as I'm not able to reproduce it reliable, I won't make any conclusions yet.

**Comment by fk** [comment]
Hmmmm, I just changed the extension of one of the `using-gatsby-image` [example images](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-gatsby-image/src/images) to `jpeg` and everything seems to work fine. :/

@JanneVincit Are you also experiencing this in the context of Contenful like @tylermenezes?

**Comment by tylermenezes** [comment]
Renaming the file from .jpeg -> .jpg in Contentful was the solution which solved _my_ problem, but the error message is extremely generic, and when I looked into the code while trying to troubleshoot, it seems like _any_ error will result in this message. A better solution is probably to improve the error message quality, but IIRC that requires a fix from both Gatsby and Potrace.

**Comment by dotlouis** [comment]
Still having the issue here. Happens on Netlify but not in local. Hard to pinpoint the problem.

**Comment by Damex989** [comment]
@dotlouis Hi, i'm having the same problem when deploying to Netlify, have you find a solution ?

**Comment by tylermenezes** [comment]
@dotlouis @Damex989 Because the error message is super generic, it's hard to tell what "the problem" is. If you're having a problem on Netlify but not on local builds, it's likely a different error entirely.

What has changed since the last successful build? Not just code-wise, but also in the CMS? If you can help narrow the problem down I might be able to help figure out what's causing your particular error.

**Comment by DanielAlejandroMontesRodriguez** [comment]
@tylermenezes Thank you for the response, it's going to sound weird but sometimes it builds correctly sometimes not, i'm using Contentful - Gatsby - Netlify, and i think it's the same error you mentioned at the beginning

```
error UNHANDLED EXCEPTION

TypeError: Cannot read property 'bitmap' of undefined
  
- Potrace.js:1000 Potrace._processLoadedImage
 [repo]/[potrace]/lib/Potrace.js:1000:35

 - Potrace.js:1046 Jimp.<anonymous>
 [repo]/[potrace]/lib/Potrace.js:1046:14
  
 - index.js:85 Jimp.throwError
 [repo]/[jimp]/index.js:85:44
  
- index.js:201 ReadFileContext.callback
[repo]/[jimp]/index.js:201:44
```

**Comment by alisonjoseph** [comment]
I'm also seeing this error, only on netlify though, not locally. Did anyone having that same issue figure it out?

**Comment by DSchau** [comment]
Some debugging by @fk led to some useful insights.

1) `potrace` depends on a fairly old version of jimp (https://github.com/tooolbox/node-potrace/blob/master/package.json)
1) `jimp` has received a few minor releases, and it's possible simply bumping the dep resolves this issue

So what I'd propose we do here is (in order of quick wins, but not necessarily fixing the underlying issue):

- PR `potrace` with a bumped version of `jimp` to see if the errors reduce or disappear
  - We'll also want to validate we haven't broken anything underying in `potrace` with this change
- PR `potrace` swapping `jimp` for `sharp`
- Fork `potrace` and make some of the underlying fixes ourselves (if PRs aren't accepted or encouraged)

What will _really_ help in this issue is if there's anyone who is able to reproduce, even intermittently. I've attempted to reproduce with [this repo](https://github.com/DSchau/gatsby-issues-8301) and [this Netlify build](https://app.netlify.com/sites/sharp-visvesvaraya-7f7e26/deploys) but no luck as of yet.

**Comment by kepi0809** [comment]
the title is misleading because it isn't the jpeg extension that causes the errors (maybe file size?)

On my blog-posts page I had many jpeg files and it works without any problems but it crashes on the post pages… 

tried to filter with graphql the jpg and/or jpeg files but it still crashed (I didn't have jpg files on my blog-posts page so I thought it could be the problem but it's not) 

If anybody know anything new according to this problem we are all ears 😄

**Comment by ertrzyiks** [comment]
I spotted this exact issue on CI job, an example failure is here https://circleci.com/gh/ertrzyiks/yummy/51
The problem is gone after I stopped caching `.cache` and `public` folders between runs. Each run is clean now and doing everything from scratch. 

Still, it's quite far from repro steps, I wasn't able to narrow it down yet. I can try to debug it if it's reproducible after enabling the cache back.

**Comment by kepi0809** [comment]
> I spotted this exact issue on CI job, an example failure is here https://circleci.com/gh/ertrzyiks/yummy/51
> The problem is gone after I stopped caching `.cache` and `public` folders between runs. Each run is clean now and doing everything from scratch.
> 
> Still, it's quite far from repro steps, I wasn't able to narrow it down yet. I can try to debug it if it's reproducible after enabling the cache back.

Yeah this is unfortunately not a production ready solution... :/ On a blog with over 300 Posts the build time would radically increase :(

**Comment by quiaro** [comment]
Same as @DanielAlejandroMontesRodriguez, I'm using Gatsby + Contentful and deploying to Netlify. Locally, the builds are running fine all the time, but on Netlify I kept getting the same error that @tylermenezes originally reported.

I followed @alisonjoseph's advice and replaced all my `...GatsbyContentfulFluid_tracedSVG` fragments with `...GatsbyContentfulFluid`, and Netlify's build finally came through. So in my case, the extensions didn't seem to make a difference since I have both `.jpeg` and `.jpg` images in Contentful.

**Comment by jessepinho** [comment]
Anecdotally, I've been seeing this issue arise when using a larger `maxWidth` with a fluid image (per @kepi0809 's point). But that's also not consistent, so I can't be sure that's the issue.

**Comment by wardpeet** [comment]
Seems like a duplicate of https://github.com/gatsbyjs/gatsby/issues/12552?

**Comment by pieh** [comment]
I opened https://github.com/gatsbyjs/gatsby/pull/12927 PR that hopefully fixes that. Because of random nature of this errors I can't be 100% sure on this

**Comment by pieh** [comment]
Update on this that I forgot to mention before:
We published `gatsby-plugin-sharp@2.0.33` with potential fixes for this problem - we are not sure if this will fix all instance of it so we keep to issue open, but please update and report back if you still are hitting this issue

**Comment by vcarl** [comment]
I just stumbled upon this issue while looking for a resolution. Intermittently getting it with `gatsby-plugin-sharp@^2.0.35` and `gatsby-source-contentful@^2.0.53` (not sure if the latter is relevant). Everything seems consistent with other comments, I can work around the issue by replacing `GatsbyContentfulFluid_tracedSVG` with `GatsbyContentfulFluid`.

**Comment by idesignpixels** [comment]
As above I'm still getting this, not sure what is meant with the replacement solution?

**Comment by smakosh** [comment]
We're having the same issue with Contentful, it happens on png images as well

```
Errors:
8:04:54 PM:   vipspng: libpng read error
8:04:54 PM:   vips2png: unable to write "/tmp/f0008e9f8878b125b79e0e5adc5ed345-laf.png-5af68fa9e3d0585311eb055946514ab5..png"
8:04:54 PM:   GraphQL request:18:9
8:04:54 PM:   17 |         srcWebp
8:04:54 PM:   18 |         tracedSVG
8:04:54 PM:      |         ^
8:04:54 PM:   19 |       }
``

**Comment by tylermenezes** [comment]
You should open a brand new issue, as this seems unrelated. The error message for this is "Cannot read property 'bitmap' of undefined".

**Comment by brotzky** [comment]
We've had the same issue. When using `travedSVG` on all latest of sharp, gatsby, contentful, etc there are 2 errors:
1. Netlify bitmap error https://github.com/gatsbyjs/gatsby/issues/8301#issuecomment-450877065
2. Gatsby tracedSVG error https://github.com/gatsbyjs/gatsby/issues/8301#issuecomment-527601896

For now removing all the tracedSVG instances fixes the build but does dampen the site experience by quite a lot.

**Comment by ezekielchow** [comment]
I'm facing this issue too. Using Gatsby + Netlify + Contentful. It happens at random though.
On local, the error thrown is
```
VipsJpeg: Premature end of JPEG file
VipsJpeg: out of order read at line 464
```
On netlify, I get
```
TypeError: Cannot read property 'bitmap' of undefined

Potrace.js:1000 Potrace._processLoadedImage
[repo]/[potrace]/lib/Potrace.js:1000:35

Potrace.js:1046 Jimp.<anonymous>
[repo]/[potrace]/lib/Potrace.js:1046:14
```

**Comment by pvdz** [comment]
Going to close this issue. There have been many changes to Sharp and friends since this was opened and I feel this issue is no longer applicable to the current version of Gatsby.

If you're still seeing this issue or something that looks like something that was reported here, please open a new, specific, issue about it. And please look to confirm whether there isn't an open issue about it already.

Thanks for all your inputs
