### ISSUE TITLE
gatsby-source-wordpress query failing during production static HTML generation, works locally in develop mode

### ISSUE THREAD

**Issue by peterlazzarino** [gatsbyjs/gatsby#8386]
## Description

When deploying a new feature that works fine locally fetching wordpress posts using gatsby-source-wordpress, I get the following build error 

```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  86 | 		markdownRemark: post,
  87 | 		allWordpressPost: { edges: allPosts }
> 88 | 	} = data;
     | 	    ^
  89 | 	const { frontmatter } = post;
  90 | 	const wpPosts = allPosts;
  91 | 	return (


  WebpackError: TypeError: Cannot destructure property `edges` of 'undefined' or 'null'.
```

Even though the build seems to be fetching them just fine

```
success copy gatsby files — 0.063 s
success onPreBootstrap — 0.004 s
⠄ source and transform nodes -> wordpress__POST fetched : 1346
⠈ source and transform nodes -> wordpress__PAGE fetched : 43
⡀ source and transform nodes -> wordpress__wp_media fetched : 1880
```

### Steps to reproduce

Install gatsby-source-wordpress into a gatsby project, add wordpress config (snippet of mine is below)

```

		{
			resolve: "gatsby-source-wordpress",
			options: {
				baseUrl: process.env.WP_URL,
				hostingWPCOM: false,
				protocol: "https",
				useACF: true,
				auth: {
					htaccess_sendImmediately: false,
					htaccess_user: process.env.WP_USER,
					htaccess_pass: process.env.WP_PASSWORD
				},
				verboseOutput: false
			}
		},
```

Add posts to your graphql query below

```


	allWordpressPost(limit:5, filter: {categories: { name : {eq : "Essay Breakdown"}}}) {
		edges {
		  node {
			id
			slug
			featured_media {
				localFile {
				  	childImageSharp {
						fixed(width: 500, height: 200) {
						...GatsbyImageSharpFixed_withWebp
						}
				  	}
				}
			}
			title
			content
			excerpt
			date
			modified
			categories{
				name
			}
			template
			tags{
				name
			}
		  }
		}
	  }
```

### Expected result

This should when the build is run as it does locally

### Actual result

gatsby build fails with error listed above

### Environment

  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 61.0.2
    Safari: 11.0.3
  npmPackages:
    gatsby: ^2.0.0-rc.21 => 2.0.0-rc.21 
    gatsby-image: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-link: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4 
    gatsby-plugin-netlify: ^2.0.0-rc.6 => 2.0.0-rc.6 
    gatsby-plugin-netlify-cms: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0 
    gatsby-plugin-sass: ^2.0.0-rc.2 => 2.0.0-rc.2 
    gatsby-plugin-sharp: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-sitemap: ^2.0.0-rc.1 => 2.0.0-rc.1 
    gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.0-rc.5 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: ^2.0.1-rc.5 => 2.0.1-rc.5 
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6 
    gatsby-source-wordpress: ^3.0.1 => 3.0.1 
    gatsby-transformer-remark: ^2.1.1-rc.5 => 2.1.1-rc.5 
    gatsby-transformer-sharp: ^2.1.1-rc.3 => 2.1.1-rc.3 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment]
@peterlazzarino can you try upgrading gatsby and dependencies to their latest stable versions? We released version 2 recently, that might solve the issue for you.

(Let us know if it doesn't)

**Comment by peterlazzarino** [comment]
@kakadiadarpan still failing, updated all packages here is the new list
```
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
  Binaries:
    Yarn: 1.6.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: 2.0.6 => 2.0.6
    gatsby-image: 2.0.6 => 2.0.6
    gatsby-link: 2.0.1 => 2.0.1
    gatsby-plugin-google-fonts: 0.0.4 => 0.0.4
    gatsby-plugin-netlify: 2.0.0 => 2.0.0
    gatsby-plugin-netlify-cms: 3.0.2 => 3.0.2
    gatsby-plugin-react-helmet: 3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: 2.0.1 => 2.0.1
    gatsby-plugin-sharp: 2.0.5 => 2.0.5
    gatsby-plugin-sitemap: 2.0.1 => 2.0.1
    gatsby-plugin-styled-components: 3.0.0 => 3.0.0
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: 2.0.1 => 2.0.1
    gatsby-source-filesystem: 2.0.1 => 2.0.1
    gatsby-source-wordpress: 3.0.1 => 3.0.1
    gatsby-transformer-remark: 2.1.3 => 2.1.3
    gatsby-transformer-sharp: 2.1.1 => 2.1.1
```

**Comment by kakadiadarpan** [comment]
@peterlazzarino can you provide a reproduction repo for this? That would make it much easier to diagnose this issue

**Comment by peterlazzarino** [comment]
@kakadiadarpan here you go https://github.com/peterlazzarino/gatsby-starter-wordpress this works using 'gatsby develop' but fails using 'gatsby build'

I had to remove my user name, password and wordpress URL but the query is what is breaking is, specifically this line in my graphQL query.

```
    allWordpressPost(limit:5, filter: {categories: { name : {eq : "Essay Breakdown"}}}) {
```

When I remove the graphql filter on allWordpressPost it works, when I add it back it fails in build mode. I imagine you would need to change the category name depending on which WP site you connect this to. Mine pulls posts that have that category in dev mode since my WP site has it.

**Comment by peterlazzarino** [comment]
@kakadiadarpan is there anything else I need to follow up with on this?

**Comment by peterlazzarino** [comment]
not stale
