### ISSUE TITLE
[www] On 404 Page redirect can not navigate between pages

### ISSUE THREAD

**Issue by dial3x** [gatsbyjs/gatsby#8574]
## Description
When a 404 page is returned the page breaks

### Steps to reproduce
go to 
https://www.gatsbyjs.org/brokenpage

click on `Docs` link

### Expected result

It should navigate away from 404 page.

### Actual result
Page does not navigate away

### Environment

  System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.611.0
  npmPackages:
    gatsby: ^2.0.9 => 2.0.9
    gatsby-image: ^2.0.8 => 2.0.9
    gatsby-link: ^2.0.1 => 2.0.1
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.3
    gatsby-plugin-google-tagmanager: ^2.0.5 => 2.0.5
    gatsby-plugin-manifest: ^2.0.2 => 2.0.3
    gatsby-plugin-offline: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.0.0 => 2.0.0
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sass: ^2.0.1 => 2.0.1
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-remark-images: ^2.0.1 => 2.0.2
    gatsby-source-contentful: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.3 => 2.1.3
    gatsby-transformer-sharp: ^2.1.1 => 2.1.2

**Comment by kakadiadarpan** [comment]
@dial3x Thank you for reporting this issue. We'll take a look at this very soon.

**Comment by pieh** [comment]
Thanks for report - this is fixed in newer version of gatsby - we just need to bump gatsby dep - https://github.com/gatsbyjs/gatsby/pull/8510

**Comment by dial3x** [comment]
Can you re open this bug. It still exists on the latest version of Gatsby.

**Comment by kakadiadarpan** [comment]
I can see it working properly:

![kapture 2018-10-03 at 10 58 17](https://user-images.githubusercontent.com/10805593/46391618-811c3300-c6fb-11e8-89af-7fe165b9826c.gif)

**Comment by haruair** [comment]
Maybe cached?

**Comment by dial3x** [comment]
@kakadiadarpan  I'm still experiencing the issue as of 1.14
https://www.shine.com.au/brokenpage

**Comment by edykim** [comment]
I can see the issue on 404 page, but looks like the page still generate from 2.0.9.

```
<meta name="generator" content="Gatsby 2.0.9"/>
```

I think `package.json` doesn't update properly. Please check `npm outdated` and see which version uses. `npm update` will update the deps as well.

**Comment by dial3x** [comment]
@edykim Thanks! I'm a dope. Issue was resolved after updating. 👍
